force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX LMS Users</relationshipLabel>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SX_LMS_UsersTriggerHelper_Test.cls
/*
 * Last Modified: 2024-09-04 19:36:33
 */

/**
 * @ Author: Gary Guthrie
 * @ Create Time: 2022-11-17 12:18:40
 * @ Modified by: Gary Guthrie
 * @ Modified time: 2024-09-04 00:14:07
 * @ Description: Test class for SX_LMS_UsersTriggerHelper
 */

@IsTest
private class SX_LMS_UsersTriggerHelper_Test {
    @TestSetup static void setup() {
        TestDataFactory.insertLMSUserData();
    }
    
    @IsTest static void testUpdate() {
        System.debug('==================SX_LMS_UsersTriggerHelper_Test Update=====================');
        List<SX_LMS_User__c> lmsList = [SELECT SX_Active_User__c FROM SX_LMS_User__c];
        Test.startTest();
        for(SX_LMS_User__c lms : lmsList){
            lms.SX_Active_User__c = !lms.SX_Active_User__c;
        }
        SchooxAPI.testResponse = SchooxAPI_Test.getMockResponse(200, SchooxAPI.ApiType.UserDetails);
        update lmsList;

        Test.stopTest();
        System.assertEquals(SchooxAPI.apiError, false, 'Get API');
    }

    @IsTest static void testCreate() {
        System.debug('==================SX_LMS_UsersTriggerHelper_Test Create=====================');
        List<SX_LMS_User__c> lmsList = [SELECT SX_Active_User__c, SX_User_ID__c, SF_User__c, SF_Contact__c FROM SX_LMS_User__c WHERE SX_User_ID__c != NULL];
        Test.startTest();
        SX_LMS_User__c lmsCopy = lmsList.get(0).clone(false, false, false, false);
        lmsCopy.SX_User_ID__c = null;
        try{
            insert lmsCopy;
        } catch (Exception ex){}


        SchooxAPI.testResponse = SchooxAPI_Test.getMockResponse(200, SchooxAPI.ApiType.UserDetails);
        delete lmsList;

        Test.stopTest();
        System.assertEquals(SchooxAPI.apiError, false, 'Get API');
    }
}