force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllCoursesEXT_Test.cls
/**
 * @ Author: Gary Guthrie
 * @ Create Time: 2022-11-17 23:50:27
 * @ Modified by: Gary Guthrie
 * @ Modified time: 2022-11-18 06:50:13
 * @ Description: Test class for GetAllCoursesEXT
 */

@isTest
private class GetAllCoursesEXT_Test {
    @testSetup static void setup() {
        TestDataFactory.insertCourseData();
    }

    static testMethod void testController (){
        List<SX_Courses__c> testCourseList = [SELECT SX_Course_ID__c FROM SX_Courses__c];
        Test.startTest();
        SchooxAPI.testResponse = SchooxAPI_Test.getMockResponse(200, SchooxAPI.ApiType.AllCourse);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(testCourseList);
        GetAllCoursesEXT courseExt = new GetAllCoursesEXT(sc);
        courseExt.getBack();
        Test.stopTest();
    }
}