force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_Active__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Course Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllCoursesEXT.cls
/**
 * @ Author: Gary Guthrie
 * @ Create Time: 2022-09-06 22:37:10
 * @ Modified by: Gary Guthrie
 * @ Modified time: 2022-11-08 20:18:07
 * @ Description: Test class is GetAllCoursesEXT_Test
 */

public with sharing class GetAllCoursesEXT {
    private ApexPages.StandardSetController stdSetController;

    public GetAllCoursesEXT(ApexPages.StandardSetController ctrl) {
        this.stdSetController = ctrl;
    }

    public pageReference getBack() {
        List<SX_Courses__c> coursesToUpdate = SchooxAPI.getAllCourse(null);
        for (SX_Courses__c rec : coursesToUpdate) {
            rec.SX_Course_Active__c = true;
        }

        upsert coursesToUpdate SX_Course_ID__c;
        System.debug('coursesToUpdate: ' + coursesToUpdate.size());
        return this.stdSetController.cancel();
    }
}