force-app/main/default/objects/Historical_Order__c/Historical_Order__c.object-meta.xml
<CustomObject>
    <label>Historical Order</label>
    <nameField>
        <displayFormat>H-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Billing_Company__c</fullName>
    <label>Billing Company</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Billing_FirstName__c</fullName>
    <label>Billing FirstName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_LastName__c.field-meta.xml
<CustomField>
    <fullName>Billing_LastName__c</fullName>
    <label>Billing LastName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Phone__c</fullName>
    <label>Billing Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/FFP_Professional_Role__c.field-meta.xml
<CustomField>
    <fullName>FFP_Professional_Role__c</fullName>
    <label>FFP Professional Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behavioral Consultant</fullName>
            </value>
            <value>
                <fullName>CSR</fullName>
            </value>
            <value>
                <fullName>Dog Walker</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Assistant Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Technician Program</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Kennel Attendant/Technician</fullName>
            </value>
            <value>
                <fullName>Other (Non-Veterinary)</fullName>
            </value>
            <value>
                <fullName>Other (Veterinary)</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Practice Manager</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Team Admin</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Technician Student</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Veterinary Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Group_Role__c.field-meta.xml
<CustomField>
    <fullName>Group_Role__c</fullName>
    <label>Group Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>No Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Guid__c.field-meta.xml
<CustomField>
    <fullName>Guid__c</fullName>
    <label>Guid</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Member_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Group__c</fullName>
    <label>Member of Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Post_Author__c</fullName>
    <label>Post Author</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Modified__c.field-meta.xml
<CustomField>
    <fullName>Post_Modified__c</fullName>
    <label>Post Modified</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Name__c.field-meta.xml
<CustomField>
    <fullName>Post_Name__c</fullName>
    <label>Post Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Title__c.field-meta.xml
<CustomField>
    <fullName>Post_Title__c</fullName>
    <label>Post Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/SF_Order__c.field-meta.xml
<CustomField>
    <fullName>SF_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Historical Orders</relationshipLabel>
    <relationshipName>Historical_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/Historical_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Historical Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historical Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Order_Item__c/fields/Historical_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Id__c</fullName>
    <label>Historical Order Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Historical_Order_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Item_Id__c</fullName>
    <label>Historical Order Item Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Successful_Insert__c.field-meta.xml
<CustomField>
    <fullName>Successful_Insert__c</fullName>
    <label>Successful Insert</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BUpdateIncorrectOrderDatesTest.cls
@IsTest
public class B2BUpdateIncorrectOrderDatesTest {

    @TestSetup static void makeData(){
        
        B2BTestDataFactory.createWebStore();
        String webStoreId  = [SELECT Id FROM WebStore WHERE Name = 'TestWebStore' LIMIT 1].Id;
        String accountId = B2BTestDataFactory.createAccount();
        String contactId = B2BTestDataFactory.createContact(accountId);
        User user = B2BTestDataFactory.createCommunityUser(contactId);
        String productId = B2BTestDataFactory.createProduct();

        Id orderId = B2BTestDataFactory.createOrder(accountId, productId);

        //Create Historical Order
        Historical_Order__c ho = new Historical_Order__c();
        ho.Historical_Order_Id__c = '459312';
        ho.Post_Author__c = 1;
        ho.Post_Date__c = Date.valueOf('2017-04-20');
        ho.Post_Title__c = 'Order &ndash; April 20, 2017 @ 05:04 PM';
        ho.Post_Name__c = 'order-apr-20-2017-1104-pm';
        ho.Post_Modified__c = Date.valueOf('2017-04-20');
        ho.Guid__c = 'https://stg-fearfreepetsmainwebsite-stage.kinsta.cloud/?post_type=shop_order&#038;p=45931';
        ho.Billing_FirstName__c = 'Test';
        ho.Billing_LastName__c = 'Toay';
        ho.Billing_Company__c = 'Midwest Veterinary Supply';
        ho.Billing_Email__c = 'test.123+1@gmail.com';
        ho.Billing_Phone__c = '402-677-3244';
        ho.Billing_Address__CountryCode__s = 'US';
        ho.FFP_Professional_Role__c = 'Faculty';
        ho.First_Name__c = 'Test';
        ho.Last_Name__c = 'Toay';
        ho.Group_Role__c = 'Leader';
        ho.Member_of_Group__c = '440830';
        ho.Successful_Insert__c = 'Pending';
        ho.User_Id__c = '12629';
        ho.Shipping_Address__CountryCode__s = 'US'; 
        ho.Date_Created__c = System.now().addDays(-10);
        ho.Order_Date__c = System.today().addDays(-12);
        ho.SF_Order__c = orderId;

        insert ho;

        //Create Historical OrderItem
        Historical_Order_Item__c hoi = new Historical_Order_Item__c();
        hoi.Historical_Order_Item_Id__c = '1234567';
        hoi.Historical_Order_Id__c = '459312';
        hoi.Product_Id__c = '234567';
        hoi.Quantity__c = 1;
        hoi.Line_Total__c = 5;
        
        insert hoi;
    }

    @isTest
    static void testBatchUpdatesOrdersAndSummaries() {
        Test.startTest();
        Database.executeBatch(new B2BUpdateIncorrectOrderDates(), 50);
        Test.stopTest();
    }

    @isTest
    static void testOrderPrepException() {
        B2BUpdateIncorrectOrderDates.testThrowPrepException = true;
        Test.startTest();
        Database.executeBatch(new B2BUpdateIncorrectOrderDates(), 50);
        Test.stopTest();
        B2BUpdateIncorrectOrderDates.testThrowPrepException = false;
    }

    @isTest
    static void testSummaryUpdateException() {
        B2BUpdateIncorrectOrderDates.testThrowSummaryUpdateException = true;
        Test.startTest();
        Database.executeBatch(new B2BUpdateIncorrectOrderDates(), 50);
        Test.stopTest();
        B2BUpdateIncorrectOrderDates.testThrowSummaryUpdateException = false;
    }
}