force-app/main/default/objects/CartItem/fields/Individual_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Individual_Membership_Assignment__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup for Previous Individual Membership Assignment</description>
    <inlineHelpText>Lookup for Previous Individual Membership Assignment</inlineHelpText>
    <label>Individual Membership Assignment</label>
    <referenceTo>Account_Membership__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CartItem/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BCustomPricingService.cls
public without sharing class B2BCustomPricingService extends commercestorepricing.PricingService {

    @TestVisible
    private static String testCartId;

    public override commercestorepricing.TransactionalPricingResponse processTransactionalPrice(commercestorepricing.TransactionalPricingRequest request) {

        String cartId = B2BUtils.getAccountActiveOrCheckoutWebCart();

        if (Test.isRunningTest() && testCartId != null) {
            cartId = testCartId;
        }

        List<CartItem> cartItems = [
            SELECT Id, Product2Id, Product2.Membership__r.Renewal_Amount__c, Individual_Membership_Assignment__c, Practice_Level_Membership_Assignment__c
            FROM CartItem
            WHERE CartId = :cartId
            AND Type = 'Product'
        ];
        
        commercestorepricing.TransactionalPricingResponse pricingResponse;
        if(!Test.isRunningTest()){
            pricingResponse = super.processTransactionalPrice(request);
        } else {
            pricingResponse = B2BTransactionalPricingResponseMock.processTransactionalPrice();
        }
        commercestorepricing.TxnPricingResponseItemCollection responseItems = pricingResponse.getTxnPricingResponseItems();

        Decimal totalListPrice = 0;
        Decimal totalProductAmount = 0;

        for (Integer i = 0; i < responseItems.size(); i++) {
            commercestorepricing.TransactionalPricingResponseItem item = responseItems.get(i);
            String productId = item.getProductId();
            Decimal quantity = item.getQuantity();

            Decimal productPrice = null;

            for(CartItem ci : cartItems) {
                if(ci.Product2Id == productId && (ci.Individual_Membership_Assignment__c != null || ci.Practice_Level_Membership_Assignment__c != null)) {
                    productPrice = ci.Product2.Membership__r.Renewal_Amount__c;
                    break;
                }
            }
            
            if (productPrice != null) {
                //Use renewal price
                item.setUnitPrice(productPrice);
                item.setListPrice(productPrice);

                Decimal totalPrice = quantity * productPrice;

                item.setTotalLineAmount(totalPrice);
                item.setTotalListPrice(totalPrice);
                item.setTotalPrice(totalPrice);

                totalListPrice += totalPrice;
                totalProductAmount += totalPrice;
            } else {
                // Use default pricing
                totalListPrice += item.getTotalListPrice();
                totalProductAmount += item.getTotalLineAmount();
            }
        }

        pricingResponse.setTotalListPrice(totalListPrice);
        pricingResponse.setTotalProductAmount(totalProductAmount);

        Decimal totalAdjustmentAmount = pricingResponse.getTotalAdjustmentAmount() != null
            ? pricingResponse.getTotalAdjustmentAmount()
            : 0;

        pricingResponse.setTotalAmount(totalProductAmount + totalAdjustmentAmount);

        return pricingResponse;
    }
}