force-app/main/default/objects/SX_Job__c/SX_Job__c.object-meta.xml
<CustomObject>
    <description>Tracks the Schoox LMS Jobs along with corresponding Schoox IDs</description>
    <label>SX Job</label>
    <nameField>
        <label>SX Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Job__c/fields/SX_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Job_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Job ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllJobsEXT.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-10-22 23:00:03
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:41:30
 * @ Description: test class is GetAllJobsEXT_Test
 */

public with sharing class GetAllJobsEXT {
    private ApexPages.StandardSetController stdSetController;

    public GetAllJobsEXT(ApexPages.StandardSetController ctrl) {
        this.stdSetController = ctrl;
    }

    public pageReference getBack() {
        List<SX_Job__c> sxJobList = SchooxAPI.getAllJob();

        upsert sxJobList SX_Job_ID__c;
        System.debug('sxJobList: ' + sxJobList.size());
        return this.stdSetController.cancel();
    }
}