force-app/main/default/objects/Historical_Membership__c/Historical_Membership__c.object-meta.xml
<CustomObject>
    <label>Historical Membership</label>
    <nameField>
        <displayFormat>HM-{00000}</displayFormat>
        <label>Historical Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Membership__c/fields/Course_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_Id__c</fullName>
    <label>Course Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/Historical_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Id__c</fullName>
    <label>Historical Order Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/Successful_Insert__c.field-meta.xml
<CustomField>
    <fullName>Successful_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Successful Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/User_Membership_Date__c.field-meta.xml
<CustomField>
    <fullName>User_Membership_Date__c</fullName>
    <label>User Membership Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Practice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/WC_Id__c.field-meta.xml
<CustomField>
    <fullName>WC_Id__c</fullName>
    <label>WC Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/WC_Id__c.field-meta.xml
<CustomField>
    <fullName>WC_Id__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/B2BCreateHistoricalMembershipsBatchTest.cls
@isTest
public class B2BCreateHistoricalMembershipsBatchTest {
    
    @TestSetup static void makeData(){
        Historical_Membership__c hm = new Historical_Membership__c();
        hm.Course_Id__c = '12345';
        hm.Product_Id__c = '234567';
        hm.User_Membership_Date__c = Date.valueOf('2020-09-10');
        hm.Start_Date__c = Date.valueOf('2020-09-09');
        hm.End_Date__c = Date.valueOf('2022-09-09');
        hm.Historical_Order_Id__c = '45176';
        hm.User_Id__c = '888';
        hm.Cancelled_Date__c = Date.valueOf('2022-07-02');
        hm.Successful_Insert__c = false;

        insert hm;

        Historical_Membership__c hm1 = new Historical_Membership__c();
        hm1.Course_Id__c = '123456';
        hm1.Product_Id__c = '934567';
        hm1.User_Membership_Date__c = Date.valueOf('2020-09-10');
        hm1.Start_Date__c = Date.valueOf('2020-09-09');
        hm1.End_Date__c = Date.valueOf('2022-09-09');
        hm1.Historical_Order_Id__c = '45176';
        hm1.User_Id__c = '888';
        hm1.Cancelled_Date__c = Date.valueOf('2022-07-02');
        hm1.Successful_Insert__c = false;

        insert hm1;

        //Create Memberships
        Membership__c individualMembership = new Membership__c();
        individualMembership.Membership_Level__c = 'Individual';
        individualMembership.Name = 'Test Individual Membership';

        insert individualMembership;

        Membership__c practiceMembership = new Membership__c();
        practiceMembership.Membership_Level__c = 'Practice';
        practiceMembership.Name = 'Test Practice Membership';

        insert practiceMembership;

        //Create Products
        Product2 imp = new Product2(
            Name = 'Individual Membership Product',
            WC_Id__c = '234567',
            Membership__c = individualMembership.Id
        );
        insert imp;

        Product2 pmp = new Product2(
            Name = 'Practice Membership Product',
            WC_Id__c = '934567',
            Membership__c = practiceMembership.Id
        );
        insert pmp;
    }

    @isTest static void testCreateHistoricalMembershipBatch_noMembership() {

        Test.StartTest();
        B2BCreateHistoricalMembershipsBatch b = new B2BCreateHistoricalMembershipsBatch();
        Database.executeBatch(b);
        Test.StopTest();
    }

}