force-app/main/default/objects/Account/fields/Account_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Code</label>
    <referenceTo>Account_Code__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Code__c/Account_Code__c.object-meta.xml
<CustomObject>
    <label>Account Code</label>
    <nameField>
        <label>Account Code Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <formula>Contact.Account.Admin_Account__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/B2BAccountCodeControllerTest.cls
@isTest
public class B2BAccountCodeControllerTest {
    
    @TestSetup static void makeData(){
        B2BTestDataFactory.createWebStore();
        String webStoreId  = [SELECT Id FROM WebStore WHERE Name = 'TestWebStore' LIMIT 1].Id;
        String accountId = B2BTestDataFactory.createAccount();
        String contactId = B2BTestDataFactory.createContact(accountId);
        User user = B2BTestDataFactory.createCommunityUser(contactId);
        B2BTestDataFactory.createWebCart(webStoreId, accountId, user.Id);

        Account_Code__c ac = new Account_Code__c(
            Name = 'Test Account Code',
            Code__c = '12345'
        );
        insert ac;
    }

    @isTest static void testUpdateAccountFields() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BAccountCodeController.updateAccountFields('12345');
        }
        Test.StopTest();
    }

    @isTest static void testUpdateAccountFields_teamAdmin() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Account businessAccount = new Account(
            Name = 'Test Business Account'
        );
        insert businessAccount;

        Account account = [SELECT Id, Business__c, Admin_Account__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        account.Admin_Account__c = true;
        update account;

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BAccountCodeController.updateAccountFields('12345');
        }
        Test.StopTest();
    }

    @isTest static void testUpdateAccountFields_noCode() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BAccountCodeController.updateAccountFields('2345');
        }
        Test.StopTest();
    }

    @isTest static void testUpdateAccountFields_null() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BAccountCodeController.updateAccountFields(null);
        }
        Test.StopTest();
    }

    @isTest static void testUpdateAccountFields_exception() {

        Boolean result;
        Test.StartTest();
        try {
            result = B2BAccountCodeController.updateAccountFields('12345');
        }
        catch(Exception e) {}
        Test.StopTest();
    }

    @isTest static void testManageAccountCode() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        B2BAccountCodeController.AccountCodeWrapper result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BAccountCodeController.manageAccountCode();
        }
        Test.StopTest();
    }

    @isTest static void testDeleteActiveCarts() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Test.StartTest();
        System.runAs(user) {
            B2BAccountCodeController.deleteActiveCarts();
        }
        Test.StopTest();
    }

    @isTest static void testDeleteActiveCarts_exception() {

        Test.StartTest();
        try {
            B2BAccountCodeController.deleteActiveCarts();
        }
        catch(Exception e) {}
        Test.StopTest();
    }
}