force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Historical_Jobs_Assigned__c.field-meta.xml
<CustomField>
    <fullName>Historical_Jobs_Assigned__c</fullName>
    <label>Historical Jobs Assigned</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Succesful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>Skipped</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BBuyerGroupsAssignmentBatch.cls
global class B2BBuyerGroupsAssignmentBatch implements Database.Batchable<SObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext bc) {
        Integer a = 1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        a=1;
        
        return Database.getQueryLocator([
            SELECT Id 
            FROM Account 
            WHERE Historical_Jobs_Assigned__c = 'Succesful' AND Admin_Account__c = true
        ]);
    }

    global void execute(Database.BatchableContext bc, List<SObject> scope) {
        List<Account> accounts = (List<Account>)scope;

        for (Account acc : accounts) {
            try {
                B2BBuyerGroupAssignemntController.handleBuyerGroupsForAccount(acc);
            } catch (Exception e) {
                String errorMessage = 'Failed to assign/unassign buyer groups for Account Id: ' + acc.Id +
                                      ' | Error: ' + e.getMessage();
                B2BHandleCustomException.LogException(
                    new BuyerGroupAssignmentException(errorMessage),
                    'Buyer Group Assignment',
                    'Batch Execution'
                );
            }
        }
    }

    global void finish(Database.BatchableContext bc) {}

    public class BuyerGroupAssignmentException extends Exception {}
}