force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/Buyer_Group_Membership__c.object-meta.xml
<CustomObject>
    <label>Buyer Group Membership</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Buyer Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyer Group Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Buyer_Group__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Group</label>
    <referenceTo>BuyerGroup</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/B2BBuyerGroupAssignmentService.cls
/**
 * @description       : 
 * @author            : Poojitha Anthati
 * @group             : 
 * @last modified on  : 09-18-2025
 * @last modified by  : Poojitha Anthati
**/
public class B2BBuyerGroupAssignmentService {
    public static List<String> getEligibleILMABuyerGroups(Account_Membership__c iLMA) {
        Account account = B2BBuyerGroupAssignmentServiceHelper.getAccountById(String.valueOf(iLMA.Account_Id__c));
        List<Buyer_Group_Membership__c> buyerGroupMembershipList = 
            B2BBuyerGroupAssignmentServiceHelper.getEligibleILMABuyerGroups(iLMA.Membership__c, iLMA.Certified__c, account.Admin_Account__c);
        
        Set<String> buyerGroupIdsSet = new Set<String>();
        for (Buyer_Group_Membership__c bgm : buyerGroupMembershipList) {
            buyerGroupIdsSet.add(bgm.Buyer_Group__c);
        }
        
        List<String> buyerGroupIds = new List<String>(buyerGroupIdsSet);
        List<BuyerGroupMember> duplicateBuyerGroupList = 
            B2BBuyerGroupAssignmentServiceHelper.getExistingBuyerGroupAssignments(String.valueOf(iLMA.Account_Id__c), buyerGroupIds);
        
        Set<String> duplicateBuyerGroupIds = new Set<String>();

        if(duplicateBuyerGroupList != null) {
            for (BuyerGroupMember duplicate : duplicateBuyerGroupList) {
                duplicateBuyerGroupIds.add(duplicate.BuyerGroupId);
            }
        }
        
        List<String> uniqueBuyerGroupIds = new List<String>();
        for (String buyerGroupId : buyerGroupIds) {
            if (!duplicateBuyerGroupIds.contains(buyerGroupId)) {
                uniqueBuyerGroupIds.add(buyerGroupId);
            }
        }
        
        return uniqueBuyerGroupIds;
    }

    public static List<String> getInEligibleILMABuyerGroups(Account_Membership__c iLMA) {
        Account account = B2BBuyerGroupAssignmentServiceHelper.getAccountById(String.valueOf(iLMA.Account_Id__c));
        List<Buyer_Group_Membership__c> buyerGroupMembershipList = 
            B2BBuyerGroupAssignmentServiceHelper.getInEligibleILMABuyerGroups(iLMA.Membership__c, iLMA.Certified__c, !account.Admin_Account__c);
        
        Set<String> buyerGroupIdsSet = new Set<String>();
        for (Buyer_Group_Membership__c bgm : buyerGroupMembershipList) {
            buyerGroupIdsSet.add(bgm.Buyer_Group__c);
        }
        
        List<String> buyerGroupIds = new List<String>(buyerGroupIdsSet);
        return buyerGroupIds;
    }

    public static void createBuyerGroupMembers(List<String> buyerGroupIdList, String accountId) {
        
        List<BuyerGroupMember> buyerGroupMembersToCreate = new List<BuyerGroupMember>();
        for (String buyerGroupId : buyerGroupIdList) {
            BuyerGroupMember buyerGroupMember = new BuyerGroupMember();
            buyerGroupMember.BuyerId = accountId;
            buyerGroupMember.BuyerGroupId = buyerGroupId;
            buyerGroupMembersToCreate.add(buyerGroupMember);
        }

        insert buyerGroupMembersToCreate;
    }

    public static void deleteBuyerGroupMembers(List<String> buyerGroupIdsToUnassign, String accountId) {
        
        List<BuyerGroupMember> buyerGroupMembersToDelete = B2BBuyerGroupAssignmentServiceHelper.getExistingBuyerGroupAssignments(accountId, buyerGroupIdsToUnassign);

        if(buyerGroupMembersToDelete != null) {
            delete buyerGroupMembersToDelete;
        }
    }

    public static List<Account_Membership__c> getActiveMemberships(String accountId) {
        try {
            List<Account_Membership__c> activeILMAs = B2BBuyerGroupAssignmentServiceHelper.getActiveIndividualMembershipAssignments(accountId);
            
            if(activeILMAs != null) {
                Map<String, Account_Membership__c> uniqueMembershipMap = new Map<String, Account_Membership__c>();
    
                for (Account_Membership__c am : activeILMAs) {
                    if (!uniqueMembershipMap.containsKey(am.Membership__c)) {
                        uniqueMembershipMap.put(am.Membership__c, am);
                    }
                }
    
                List<Account_Membership__c> uniqueAccountMemberships = new List<Account_Membership__c>(uniqueMembershipMap.values());
                return uniqueAccountMemberships;
            }
            return activeILMAs;
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BBuyerGroupAssignmentService', 'getActiveMemberships');
            return null;
        }
    }

    public static List<String> getEligibleBuyerGroups(Account_Membership__c iLMA) {
        Account account = B2BBuyerGroupAssignmentServiceHelper.getAccountById(String.valueOf(iLMA.Account_Id__c));
        List<Buyer_Group_Membership__c> buyerGroupMembershipList = 
            B2BBuyerGroupAssignmentServiceHelper.getEligibleILMABuyerGroups(iLMA.Membership__c, iLMA.Certified__c, account.Admin_Account__c);
        
        Set<String> buyerGroupIdsSet = new Set<String>();
        for (Buyer_Group_Membership__c bgm : buyerGroupMembershipList) {
            buyerGroupIdsSet.add(bgm.Buyer_Group__c);
        }
        
        return new List<String>(buyerGroupIdsSet);
    }

    public static List<String> getAllBuyerGroupAssignments(String accountId) {
        try {
            List<BuyerGroupMember> allBuyerGroups = B2BBuyerGroupAssignmentServiceHelper.getAllBuyerGroupAssignments(accountId);
            List<String> buyerGroupIds = new List<String>();
            
            if(allBuyerGroups != null) {
                for (BuyerGroupMember bgm : allBuyerGroups) {
                    buyerGroupIds.add(bgm.BuyerGroupId);
                }
            }
            return buyerGroupIds; 
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BBuyerGroupAssignmentService', 'getAllBuyerGroupAssignments');
            return null;
        }
    }
}