force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CartItem/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Cart Items</relationshipLabel>
    <relationshipName>Cart_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Level Membership</fullName>
            </value>
            <value>
                <fullName>Practice Level Membership</fullName>
            </value>
            <value>
                <fullName>Certification Kit</fullName>
            </value>
            <value>
                <fullName>Individual Academia Membership</fullName>
            </value>
            <value>
                <fullName>Permanent Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WebCart/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BCustomAddToCartController.cls
public without sharing class B2BCustomAddToCartController {
    
    @AuraEnabled
    public static Boolean isVariantProduct(String productId) {
        String productClass = String.valueOf([SELECT ProductClass FROM Product2 WHERE Id = :productId]?.ProductClass);

        if (productClass == 'VariationParent') 
            return false;
        else
            return true;
    }

    @AuraEnabled
    public static String getProductGroup(String productId) {

        List<Product2> product = [SELECT Id, Product_Group__c FROM Product2 WHERE Id =:productId];

        if(product.size() > 0) {
            return product[0].Product_Group__c;
        }
        return null;
    }

    @AuraEnabled(cacheable=true)
    public static Boolean isAdminAccount() {
        String accountId = B2BUtils.getUserAccountID();
        List<Account> account = [SELECT Id, Admin_Account__c FROM Account WHERE Id =:accountId];

        return account[0].Admin_Account__c;
    }

    @AuraEnabled
    public static List<Account_Membership__c> getIndividualLevelMemberships(String productId) {

        Product2 product = [SELECT Id, Membership__c FROM Product2 WHERE Id =: productId];

        String membershipId = product.Membership__c;
        String accountId = B2BUtils.getUserAccountID();

        List<Account_Membership__c> membershipList = [SELECT Id FROM Account_Membership__c 
                                                      WHERE Membership__c  =:membershipId 
                                                      AND Parent_Id__c =:accountId
                                                      AND Status__c = 'Active'
                                                     ];
        
        return membershipList;
    }

    @AuraEnabled
    public static List<Practice_Level_Membership_Assignment__c> getPracticeLevelMemberships(String productId) {

        Product2 product = [SELECT Id, Membership__c FROM Product2 WHERE Id =: productId];

        String accountId = B2BUtils.getUserAccountID();
        Account account = [SELECT Id, Business__c FROM Account WHERE Id =:accountId];

        List<Practice_Level_Membership_Assignment__c > practiceLevelMemberships = new List<Practice_Level_Membership_Assignment__c >();
        if(account.Business__c != null) {
            practiceLevelMemberships = [SELECT Id FROM Practice_Level_Membership_Assignment__c 
                                        WHERE Membership__c  =:product.Membership__c 
                                        AND Business_Account__c =:account.Business__c
                                        AND Status__c = 'Active'
                                       ];
        }
        
        return practiceLevelMemberships;
    }

    @AuraEnabled
    public static Boolean isProductPresentInCart(String productId) {
        String accountId;
        if(UserInfo.getUserType() == 'Guest') {
            accountId = [SELECT Id FROM GuestBuyerProfile LIMIT 1].Id;
        } else  {
            accountId = B2BUtils.getUserAccountID();
        }

        List<WebCart> cart = [SELECT Id FROM WebCart 
                              WHERE AccountId =:accountId AND (Status = 'Active' OR Status = 'Checkout')
                              Order By CreatedDate Desc LIMIT 1];

        if(cart.size() > 0) {
            List<CartItem> cartItems = [SELECT Id, Product2Id
                                        FROM CartItem
                                        WHERE CartId =:cart[0].Id
                                       ];
            
            if(cartItems.size() > 0) {
                for(CartItem ci : cartItems) {
                    if(ci.Product2Id == productId) {
                        return true;
                    }
                }
            }                             
        }
        return false;
    }
}