force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>ADDMONTHS( Start_Date__c ,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>formula- ADDMONTHS( Start_Date__c ,12)</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Renewal_DVM_Count__c.field-meta.xml
<CustomField>
    <fullName>Renewal_DVM_Count__c</fullName>
    <label>Renewal DVM Count</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Renewal_DVM_Count_Max__c.field-meta.xml
<CustomField>
    <fullName>Renewal_DVM_Count_Max__c</fullName>
    <label>Renewal DVM Count Max</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Renewal_DVM_Count_Min__c.field-meta.xml
<CustomField>
    <fullName>Renewal_DVM_Count_Min__c</fullName>
    <label>Renewal DVM Count Min</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/B2BPracticeLevelRenewalsHelper.cls
public with sharing class B2BPracticeLevelRenewalsHelper {

    public static List<Practice_Level_Membership_Assignment__c> getEligibleMembershipAssignments(String businessAccountId) {
        try {
            Map<String,String> minMaxDates = B2BUtils.calculateMinMaxRenewalOffsetRange();
            String minDate = minMaxDates.get('minDate');
            String maxDate = minMaxDates.get('maxDate');
            
            String queryString = 'SELECT Id, Business_Account__c, Membership__c, Renewal_DVM_Count__c' +
                                 ' FROM Practice_Level_Membership_Assignment__c' +
                                 ' WHERE Expiration_Date__c >= ' + minDate + ' AND Expiration_Date__c <= ' + maxDate + 
                                 ' AND Status__c != \'Canceled\'' +
                                 ' AND Business_Account__c = :businessAccountId';

            List<Practice_Level_Membership_Assignment__c> memberships = Database.query(queryString);
            
            return memberships.isEmpty() ? null : memberships;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getEligibleMembershipAssignments');
            return null;
        }
    }
    
    public static String getWebStoreIdByName(String storeName) {
        try {
            return [
                SELECT Id 
                FROM WebStore 
                WHERE Name = :storeName 
                LIMIT 1
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getWebStoreIdByName');
            return null;
        }
    }

    public static String getRenewalProductId(String membershipId, Decimal renewalDVMCount) {
        try {
            return [
                SELECT Id, Membership__c 
                FROM Product2 
                WHERE Renewal_DVM_Count_MIN__c <= :renewalDVMCount 
                AND Renewal_DVM_Count_MAX__c >= :renewalDVMCount 
                AND Membership__c = :membershipId
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getRenewalProductId');
            return null;
        }
    }

    public static Decimal getRenewalProductPrice(String productId, String businessAccountId) {
        try {
            String teamAdminId = [
                SELECT Id FROM
                Account
                WHERE Business__c =:businessAccountId
                AND IsPersonAccount = TRUE
                AND Admin_Account__c = TRUE
            ].Id;

            return B2BUtils.getProductPriceByAccountId(productId, teamAdminId);

        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getRenewalProductPrice');
            return null;
        }
    }
    
    public static Date getEffectiveOrderDate(String paymentTerms) {
        try {
            return B2BUtils.getTargetRenewalDate();
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getEffectiveOrderDate');
            return null;
        }
    }

    public static String getOrderDeliveryMethodId() {
        try {
            return [
                SELECT Id, Name 
                FROM OrderDeliveryMethod
                LIMIT 1
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPracticeLevelRenewalsHelper', 'getOrderDeliveryMethodId');
            return null;
        }
    }   
}