force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/Buyer_Group_Membership__c.object-meta.xml
<CustomObject>
    <label>Buyer Group Membership</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Buyer Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyer Group Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Buyer_Group__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Group</label>
    <referenceTo>BuyerGroup</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
            </value>
            <value>
                <fullName>Non Admin</fullName>
            </value>
            <value>
                <fullName>All</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/B2BBuyerGroupAssignmentServiceHelper.cls
public class B2BBuyerGroupAssignmentServiceHelper {
    public static List<Buyer_Group_Membership__c> getEligibleILMABuyerGroups(String membershipId, Boolean isCertified, Boolean isAdmin) {
        try {
            String role = getBuyerGroupRole(isAdmin);
            String query = 'SELECT Id, Membership__c, Buyer_Group__c' + 
                            ' FROM Buyer_Group_Membership__c' + 
                            ' WHERE (Membership__c =:membershipId OR Membership__c = NULL)' + 
                            ' AND (Role__c = \'All\' OR Role__c =:role)';

            if(!isCertified) {
                query += ' AND Certified__c = :isCertified';
            }

            return Database.query(query);
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BBuyerGroupAssignmentServiceHelper', 'getEligibleILMABuyerGroups');
            return null;
        }
    }

    public static List<Buyer_Group_Membership__c> getInEligibleILMABuyerGroups(String membershipId, Boolean isCertified, Boolean isAdmin) {
        try {
            String role = getBuyerGroupRole(isAdmin);
            String query = 'SELECT Id, Buyer_Group__c, Role__c' + 
                           ' FROM Buyer_Group_Membership__c' + 
                           ' WHERE (Membership__c =:membershipId OR Membership__c = NULL)' + 
                           ' AND Role__c =:role';

            if(!isCertified) {
                query += ' AND Certified__c = :isCertified';
            }

            return Database.query(query);
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BBuyerGroupAssignmentServiceHelper', 'getInEligibleILMABuyerGroups');
            return null;
        }
    }

    public static Account getAccountById(String accountId) {
        return [
            SELECT Id, Admin_Account__c
            FROM Account
            WHERE Id =:accountId
        ];
    }

    public static String getBuyerGroupRole(Boolean isAdmin) {
        if (isAdmin == true) {
            return 'Admin';
        }
        return 'Non Admin';
    }

    public static List<Account_Membership__c> getActiveIndividualMembershipAssignments(String accountId) {
        try {
            List<Account_Membership__c> accountMemberships = [
                SELECT Id, Name, Certified__c, Membership__c, Status__c, Account_Id__c 
                FROM Account_Membership__c 
                WHERE Account_Id__c = :accountId
                AND Status__c = 'Active'
                ORDER BY CreatedDate DESC
            ];
            return accountMemberships.isEmpty() ? null : accountMemberships;
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BBuyerGroupAssignmentServiceHelper', 'getActiveIndividualMembershipAssignments');
            return null;
        }
    }

    public static List<BuyerGroupMember> getExistingBuyerGroupAssignments(String accountId, List<String> buyerGroupIds) {

        List<BuyerGroupMember> buyerGroupMembers = [
            SELECT Id, BuyerGroupId, BuyerId
            FROM BuyerGroupMember
            WHERE BuyerGroupId IN :buyerGroupIds
            AND BuyerId = :accountId
        ];
        return buyerGroupMembers.isEmpty() ? null : buyerGroupMembers; 
    }
}