force-app/main/default/objects/Account/fields/Admin_Account__c.field-meta.xml
<CustomField>
    <fullName>Admin_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BCreateMyTeamController.cls
public without sharing class B2BCreateMyTeamController {

    @AuraEnabled
    public static Account getAccountDetails() {
        String accountId = B2BUtils.getUserAccountID();
        List<Account> account = [SELECT Id, Admin_Account__c, Business__c
                                 FROM Account 
                                 WHERE Id =: accountId];   
        
        
        return account[0];
    }
}