force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>(Deprecated) Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email_Verified__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>(Deprecated) Billing Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
                <default>true</default>
                <label>Credit Card Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/PracticeLevelRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>PracticeLevelRenewalDate__c</fullName>
    <label>PracticeLevelRenewalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Business_Account.recordType-meta.xml
<RecordType>
    <fullName>Business_Account</fullName>
    <active>true</active>
    <label>Business Account</label>
</RecordType>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/IsRenewal__c.field-meta.xml
<CustomField>
    <fullName>IsRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRenewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Membership_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Membership_Renewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Membership Renewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous Practice Membership Assignment used for renewal</description>
    <inlineHelpText>Previous Practice Membership Assignment used for renewal</inlineHelpText>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>ADDMONTHS( Start_Date__c ,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>formula- ADDMONTHS( Start_Date__c ,12)</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <formula>Text( Business_Account__r.Payment_Terms__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Payment Terms</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Renewal_DVM_Count__c.field-meta.xml
<CustomField>
    <fullName>Renewal_DVM_Count__c</fullName>
    <label>Renewal DVM Count</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/B2BPracticeLevelRenewalsService.cls
public class B2BPracticeLevelRenewalsService {
    // private static final String WEB_STORE_NAME = System.Label.B2B_WebStore_Name;
    
    // public static List<B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment> getPracticeLevelMembershipAssignments(String businessAccountId) {
        
    //     List<Practice_Level_Membership_Assignment__c> plmasSObjectList = B2BPracticeLevelRenewalsHelper.getEligibleMembershipAssignments(businessAccountId);
        
    //     if (plmasSObjectList == null || plmasSObjectList.isEmpty()) {
    //         return null;
    //     }
        
    //     List <B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment> plmaWrapperList = new List <B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment> ();

    //     for (Practice_Level_Membership_Assignment__c plmasSObject : plmasSObjectList) {
            
    //         B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment plmaWrapper = new B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment();
            
    //         plmaWrapper.id = plmasSObject.Id;
    //         plmaWrapper.business_account = plmasSObject.Business_Account__c;
    //         plmaWrapper.membership_id = plmasSObject.Membership__c;
    //         plmaWrapper.expirationDate = plmasSObject.Expiration_Date__c;
    //         plmaWrapper.renewal_dvm_count = plmasSObject.Renewal_DVM_Count__c == 0 ? 1 : plmasSObject.Renewal_DVM_Count__c;
            
    //         plmaWrapper.renewal_product_id = B2BPracticeLevelRenewalsHelper.getRenewalProductId( plmaWrapper.membership_id, plmaWrapper.renewal_dvm_count);
    //         plmaWrapper.renewal_price = B2BPracticeLevelRenewalsHelper.getRenewalProductPrice(plmaWrapper.renewal_product_id, plmaWrapper.business_account);
            
    //         plmaWrapperList.add(plmaWrapper);
    //     }
        
    //     return plmaWrapperList;
    // } 
    
    
    // public static B2BPracticeLevelRenewalsWrapper.BusinessAccount getBusinessAccount(Account businessAccountSObject, Date renewalDate) {
        
    //     B2BPracticeLevelRenewalsWrapper.BusinessAccount businessAccount = new B2BPracticeLevelRenewalsWrapper.BusinessAccount();
        
    //     businessAccount.account_id = businessAccountSObject.Id;
    //     businessAccount.name = businessAccountSObject.Name;
    //     businessAccount.billing_email = businessAccountSObject.Billing_Email__c;
    //     businessAccount.billing_email_verified = businessAccountSObject.Billing_Email_Verified__c;
    //     businessAccount.billing_address = businessAccountSObject.BillingAddress;
    //     businessAccount.shipping_address = businessAccountSObject.BillingAddress;
    //     businessAccount.payment_terms = businessAccountSObject.Payment_Terms__c;
    //     businessAccount.practiceLevelRenewalDate = renewalDate;//businessAccountSObject.PracticeLevelRenewalDate__c;
        
    //     return businessAccount;
    // }

    // public static  B2BPracticeLevelRenewalsWrapper.Order createOrder(B2BPracticeLevelRenewalsWrapper.BusinessAccount businessAccount) {
        
    //     Order order = new Order();
    //     order.Name = businessAccount.account_id + ' Membership Renewal';
    //     order.AccountId = businessAccount.account_id;
    //     order.OrderedDate = DateTime.now();
    //     order.PoNumber = 'Membership Renewal';
    //     order.EffectiveDate = B2BPracticeLevelRenewalsHelper.getEffectiveOrderDate(businessAccount);
    //     order.SalesStoreId = B2BPracticeLevelRenewalsHelper.getWebStoreIdByName(WEB_STORE_NAME);
    //     order.Status = 'Draft';
    //     order.BillingStreet = businessAccount.billing_address.street;
    //     order.BillingCity = businessAccount.billing_address.city;
    //     order.BillingState = businessAccount.billing_address.state;
    //     order.BillingPostalCode = businessAccount.billing_address.postalCode;
    //     order.BillingCountry = businessAccount.billing_address.country;
    //     order.ShippingStreet = businessAccount.shipping_address.street;
    //     order.ShippingCity = businessAccount.shipping_address.city;
    //     order.ShippingState = businessAccount.shipping_address.state;
    //     order.ShippingPostalCode = businessAccount.shipping_address.postalCode;
    //     order.ShippingCountry = businessAccount.shipping_address.country;
    //     order.IsRenewal__c = true;
        
    //     insert order;

    //     OrderDeliveryGroup odg = new OrderDeliveryGroup();
        
    //     odg.OrderId = order.Id;
    //     odg.DeliverToName = businessAccount.name;
    //     odg.DeliverToStreet = businessAccount.shipping_address.street;
    //     odg.DeliverToCity = businessAccount.shipping_address.city;
    //     odg.DeliverToState = businessAccount.shipping_address.state;
    //     odg.DeliverToPostalCode = businessAccount.shipping_address.postalCode;
    //     odg.DeliverToCountry = businessAccount.shipping_address.country;
    //     odg.OrderDeliveryMethodId = B2BPracticeLevelRenewalsHelper.getOrderDeliveryMethodId();
    
    //     insert odg;
        
    //     B2BPracticeLevelRenewalsWrapper.Order orderWrapper = new B2BPracticeLevelRenewalsWrapper.Order();

    //     orderWrapper.id = order.Id;
    //     orderWrapper.order_delivery_group_id = odg.Id;
        
    //     return orderWrapper;
    // }

    // public static void createOrderItems( List<B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment> plmaList, B2BPracticeLevelRenewalsWrapper.Order order) {
        
    //     List<OrderItem> orderItemList = new List<OrderItem>();

    //     for (B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment plma : plmaList) {
    //         OrderItem oi = new OrderItem();
            
    //         oi.OrderId = order.id;
    //         oi.OrderDeliveryGroupId = order.order_delivery_group_id;
    //         oi.Product2Id = plma.renewal_product_id;
    //         oi.Quantity = 1;
    //         oi.UnitPrice = plma.renewal_price;
    //         oi.ListPrice = plma.renewal_price;
    //         oi.TotalLineAmount = plma.renewal_price;
    //         oi.Type = 'Order Product';
    //         oi.Membership_Renewal__c = true;
    //         oi.Practice_Membership_Assignment__c = plma.id;

    //         orderItemList.add(oi);
    //     }
        
    //     insert orderItemList;
        
    // }
}