force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>(Deprecated) Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Email_Verified__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email_Verified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>(Deprecated) Billing Email Verified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/IndividualLevelRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>IndividualLevelRenewalDate__c</fullName>
    <label>IndividualLevelRenewalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
                <default>true</default>
                <label>Credit Card Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BIndividualLevelRenewalScheduler.cls
global class B2BIndividualLevelRenewalScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {
        Map<String,String> minMaxDates = B2BUtils.calculateMinMaxRenewalOffsetRange();

        if(minMaxDates != null) {
            String minDate = minMaxDates.get('minDate');
            String maxDate = minMaxDates.get('maxDate');

            String query = 'SELECT Id, Name, Billing_Email__c, Billing_Email_Verified__c, BillingAddress, Payment_Terms__c ' +
                        'FROM Account ' + 
                        'WHERE IndividualLevelRenewalDate__c >= ' + minDate + ' AND IndividualLevelRenewalDate__c <= ' + maxDate;

            Integer batchSize = Integer.valueOf(System.Label.B2B_Individual_Level_Auto_Renewals_Batch_Size);

            B2BIndividualLevelRenewalsBatch b = new B2BIndividualLevelRenewalsBatch(query); 
            Database.executeBatch(b, batchSize);
        }
    }
}