force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>(Deprecated) Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/Historical_Order__c.object-meta.xml
<CustomObject>
    <label>Historical Order</label>
    <nameField>
        <displayFormat>H-{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Company__c.field-meta.xml
<CustomField>
    <fullName>Billing_Company__c</fullName>
    <label>Billing Company</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>Billing Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_FirstName__c.field-meta.xml
<CustomField>
    <fullName>Billing_FirstName__c</fullName>
    <label>Billing FirstName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_LastName__c.field-meta.xml
<CustomField>
    <fullName>Billing_LastName__c</fullName>
    <label>Billing LastName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Billing_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Phone__c</fullName>
    <label>Billing Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Customer_Id__c.field-meta.xml
<CustomField>
    <fullName>Customer_Id__c</fullName>
    <label>Customer Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Date_Completed__c.field-meta.xml
<CustomField>
    <fullName>Date_Completed__c</fullName>
    <label>Date Completed</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Date_Created__c.field-meta.xml
<CustomField>
    <fullName>Date_Created__c</fullName>
    <label>Date Created</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Date_Paid__c.field-meta.xml
<CustomField>
    <fullName>Date_Paid__c</fullName>
    <label>Date Paid</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/FFP_Professional_Role__c.field-meta.xml
<CustomField>
    <fullName>FFP_Professional_Role__c</fullName>
    <label>FFP Professional Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behavioral Consultant</fullName>
            </value>
            <value>
                <fullName>CSR</fullName>
            </value>
            <value>
                <fullName>Dog Walker</fullName>
            </value>
            <value>
                <fullName>Faculty</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Assistant Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Technician Program</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Kennel Attendant/Technician</fullName>
            </value>
            <value>
                <fullName>Other (Non-Veterinary)</fullName>
            </value>
            <value>
                <fullName>Other (Veterinary)</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Practice Manager</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>Team Admin</fullName>
            </value>
            <value>
                <fullName>Technician</fullName>
            </value>
            <value>
                <fullName>Technician Student</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Veterinary Student</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Group_Role__c.field-meta.xml
<CustomField>
    <fullName>Group_Role__c</fullName>
    <label>Group Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Leader</fullName>
            </value>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>No Group</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Guid__c.field-meta.xml
<CustomField>
    <fullName>Guid__c</fullName>
    <label>Guid</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Member_of_Group__c.field-meta.xml
<CustomField>
    <fullName>Member_of_Group__c</fullName>
    <label>Member of Group</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Num_Items_Sold__c.field-meta.xml
<CustomField>
    <fullName>Num_Items_Sold__c</fullName>
    <label>Num Items Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <label>Parent Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Author__c.field-meta.xml
<CustomField>
    <fullName>Post_Author__c</fullName>
    <label>Post Author</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Modified__c.field-meta.xml
<CustomField>
    <fullName>Post_Modified__c</fullName>
    <label>Post Modified</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Name__c.field-meta.xml
<CustomField>
    <fullName>Post_Name__c</fullName>
    <label>Post Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Post_Title__c.field-meta.xml
<CustomField>
    <fullName>Post_Title__c</fullName>
    <label>Post Title</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Returning_Customer__c.field-meta.xml
<CustomField>
    <fullName>Returning_Customer__c</fullName>
    <label>Returning Customer</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Shipping_Total__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Total__c</fullName>
    <label>Shipping Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>wc-cancelled</fullName>
            </value>
            <value>
                <fullName>wc-completed</fullName>
            </value>
            <value>
                <fullName>wc-failed</fullName>
            </value>
            <value>
                <fullName>wc-on-hold</fullName>
            </value>
            <value>
                <fullName>wc-pending</fullName>
            </value>
            <value>
                <fullName>wc-processing</fullName>
            </value>
            <value>
                <fullName>wc-refunded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Order__c/fields/Total_Sales__c.field-meta.xml
<CustomField>
    <fullName>Total_Sales__c</fullName>
    <label>Total Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/Historical_Order_Item__c.object-meta.xml
<CustomObject>
    <label>Historical Order Item</label>
    <nameField>
        <label>Order Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historical Order Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Order_Item__c/fields/Historical_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Id__c</fullName>
    <label>Historical Order Id</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Historical_Order_Item_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Item_Id__c</fullName>
    <label>Historical Order Item Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Product_Id__c.field-meta.xml
<CustomField>
    <fullName>Product_Id__c</fullName>
    <label>Product Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Order_Item__c/fields/Successful_Insert__c.field-meta.xml
<CustomField>
    <fullName>Successful_Insert__c</fullName>
    <label>Successful Insert</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/WC_Id__c.field-meta.xml
<CustomField>
    <fullName>WC_Id__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/B2BCreateHistoricalOrdersBatch.cls
public class B2BCreateHistoricalOrdersBatch implements Database.Batchable<sObject>, Database.Stateful {

    public B2BCreateHistoricalOrdersBatch() { }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Name, Billing_Address__City__s, Billing_Address__CountryCode__s, Billing_Address__PostalCode__s, Billing_Address__StateCode__s, Billing_Address__Street__s, Billing_Company__c, Billing_Email__c, Billing_FirstName__c, Billing_LastName__c, Billing_Phone__c, Customer_Id__c, Date_Completed__c, Date_Created__c, Date_Paid__c, Discount_Amount__c, FFP_Professional_Role__c, First_Name__c, Group_Role__c, Guid__c, Historical_Order_Id__c, Last_Name__c, Member_of_Group__c, Net_Total__c, Num_Items_Sold__c, Order_Date__c, Parent_Id__c, Post_Author__c, Post_Date__c, Post_Modified__c, Post_Name__c, Post_Title__c, Returning_Customer__c, Shipping_Address__City__s, Shipping_Address__CountryCode__s, Shipping_Address__PostalCode__s, Shipping_Address__StateCode__s, Shipping_Address__Street__s, Shipping_Total__c, Status__c, Successful_Insert__c, Tax_Total__c, Total_Sales__c, User_Id__c FROM Historical_Order__c WHERE Successful_Insert__c = false';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Historical_Order__c> scope){

        try {
            //Get WebStore Id
            String storeName = System.Label.B2B_WebStore_Name;
            String storeId = [SELECT Id FROM WebStore WHERE Name = :storeName LIMIT 1]?.Id;

            //Get Default Order Delivery Method
            String deliveryMethodId;
            List<OrderDeliveryMethod> deliveryMethod = [SELECT Id FROM OrderDeliveryMethod WHERE IsActive = true];

            if(deliveryMethod.size() > 0) {
                deliveryMethodId = deliveryMethod[0].Id;
            }
            else {
                //Get Shipping Product
                String shippingProductId;
                List<Product2> shippingProduct = [SELECT Id FROM Product2 WHERE Name = 'Delivery Charge' AND IsActive = true];

                if(shippingProduct.size() > 0) {
                    shippingProductId = shippingProduct[0].Id;
                }
                else {
                    //Create a Shipping Product
                    Product2 p = new Product2(
                        Name = 'Delivery Charge'
                    );
                    insert p;

                    shippingProductId = p.Id;
                }
                    
                //Create Default Delivery Method
                OrderDeliveryMethod odm = new OrderDeliveryMethod();
                odm.Name = 'Default Delivery Method';
                odm.Carrier = 'Fedex';
                odm.ClassOfService = 'Digital Shipping';
                odm.IsActive = true;
                odm.ProductId = shippingProductId;

                insert odm;

                deliveryMethodId = odm.Id;
            }

            //Create Maps to get AccountId and ProductId 
            Map<String, String> accountMap = new Map<String, String>();
            Map<String, String> productMap = new Map<String, String>();

            Set<String> customerEmails = new Set<String>();
            Set<String> historicalOrderIds = new Set<String>();
            for(Historical_Order__c s : scope) {
                customerEmails.add(s.Billing_Email__c);
                historicalOrderIds.add(s.Historical_Order_Id__c);
            }

            List<Account> customerAccounts = [SELECT Id, PersonEmail FROM Account WHERE PersonEmail IN :customerEmails];
            if(customerAccounts.size() > 0) {
                for(Account a : customerAccounts) {
                    accountMap.put(a.PersonEmail, a.Id);
                }
            }

            List<Product2> products = [SELECT Id, WC_Id__c FROM Product2 WHERE WC_Id__c IN :historicalOrderIds];
            if(products.size() > 0) {
                for(Product2 p : products) {         
                    productMap.put(p.WC_Id__c, p.Id);
                }
            }
            
            //List of records to insert
            List<Order> orders = new List<Order>();
            List<OrderDeliveryGroup> odgs = new List<OrderDeliveryGroup>();
            List<OrderItem> orderItems = new List<OrderItem>();

            for(Historical_Order__c s : scope){

                // Create a new Order for the Account
                Order order = new Order();
                order.Name = s.Historical_Order_Id__c;
                order.AccountId = accountMap.get(s.Billing_Email__c);
                order.OrderedDate = DateTime.now();
                order.PoNumber = s.Name;
                order.EffectiveDate = System.Today();
                order.SalesStoreId = storeId;
                order.Status = 'Draft';
                order.BillingStreet = s.Billing_Address__Street__s;
                order.BillingCity = s.Billing_Address__City__s;
                order.BillingState = s.Billing_Address__StateCode__s;
                order.BillingPostalCode = s.Billing_Address__PostalCode__s;
                order.BillingCountry = s.Billing_Address__CountryCode__s;
                order.ShippingStreet = s.Shipping_Address__Street__s;
                order.ShippingCity = s.Shipping_Address__City__s;
                order.ShippingState = s.Shipping_Address__StateCode__s;
                order.ShippingPostalCode = s.Shipping_Address__PostalCode__s;
                order.ShippingCountry = s.Shipping_Address__CountryCode__s;

                orders.add(order);
            }

            if (!orders.isEmpty()) {
                insert orders;

                for (Order order : orders) {
                    // Create Order Delivery Group for each Order
                    OrderDeliveryGroup odg = new OrderDeliveryGroup();
                    odg.orderId = order.Id;
                    odg.DeliverToName = order.Name;
                    odg.DeliverToStreet = order.ShippingStreet;
                    odg.DeliverToCity = order.ShippingCity;
                    odg.DeliverToState = order.ShippingState;
                    odg.DeliverToPostalCode = order.ShippingPostalCode;
                    odg.DeliverToCountry = order.ShippingCountry;
                    odg.OrderDeliveryMethodId = deliveryMethodId;

                    odgs.add(odg);

                    //Get Historical Order Items records for each Order
                    List<Historical_Order_Item__c > histOrderItems = [SELECT Id, Historical_Order_Item_Id__c, Historical_Order_Id__c, Product_Id__c, Quantity__c, Line_Total__c
                                                                      FROM Historical_Order_Item__c 
                                                                      WHERE Historical_Order_Id__c = :order.Name];

                    for (Historical_Order_Item__c  hoi : histOrderItems) {
                        //Create Order Item for each historical order item
                        OrderItem oi = new OrderItem();
                        oi.OrderDeliveryGroupId = null; //will assign after odgs are inserted
                        oi.OrderId =order.Id;
                        oi.Product2Id = productMap.get(hoi.Historical_Order_Id__c);
                        oi.Quantity = hoi.Quantity__c;
                        oi.UnitPrice = hoi.Line_Total__c;
                        oi.ListPrice = hoi.Line_Total__c;
                        oi.Type = 'Order Product';
                        oi.Description = hoi.Historical_Order_Item_Id__c;

                        orderItems.add(oi);
                    }
                }
            }

            if (!odgs.isEmpty()) {
                insert odgs;

                // After inserting Delivery Groups, map OrderId -> DeliveryGroupId
                Map<String, String> orderToDeliveryGroupMap = new Map<String, String>();
                for (OrderDeliveryGroup odg : odgs) {
                    orderToDeliveryGroupMap.put(odg.orderId, odg.Id);
                }

                // Update the Order Items to have the orderDeliveryGroup
                for (OrderItem orderItem : orderItems) {
                    orderItem.OrderDeliveryGroupId = orderToDeliveryGroupMap.get(orderItem.OrderId);
                }

                // Insert Order Items
                if (!orderItems.isEmpty()) {
                    insert orderItems;
                }
            }

            //Activate all the Orders
            for (Order order : orders) {
                order.Status = 'Activated';
            }
            update orders;

            //Create Order Summary and link with Order 
            for (Order order : orders) {
                ConnectApi.OrderSummaryInputRepresentation osir = new ConnectApi.OrderSummaryInputRepresentation();
                osir.orderId = order.Id;
                osir.orderLifeCycleType = 'UNMANAGED';
                ConnectApi.OrderSummaryOutputRepresentation osor = ConnectApi.OrderSummaryCreation.createOrderSummary(osir);
            }
            System.debug('##Order Summaries Inserted Successfully!');

            List<Historical_Order__c> historicalOrdersToBeUpdated = new List<Historical_Order__c>();
            for(Historical_Order__c ho : scope) {
                ho.Successful_Insert__c = true;
                historicalOrdersToBeUpdated.add(ho);
            }
            update historicalOrdersToBeUpdated;
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'Historical Orders', 'Order Creation');
        }        
    }

    public void finish(Database.BatchableContext bc){

    }
}