force-app/main/default/objects/Account/fields/Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Email__c</fullName>
    <label>(Deprecated) Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Invoice_Billing_Email__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Billing_Email__c</fullName>
    <label>Invoice Billing Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Amount_Charged__c.field-meta.xml
<CustomField>
    <fullName>Amount_Charged__c</fullName>
    <label>Amount Charged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_URL__c</fullName>
    <label>Stripe Payment URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_PDF_URL__c.field-meta.xml
<CustomField>
    <fullName>Stripe_PDF_URL__c</fullName>
    <label>Stripe PDF URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Total__c.field-meta.xml
<CustomField>
    <fullName>Total__c</fullName>
    <label>Total</label>
    <summarizedField>Invoice_Line__c.Line_Total__c</summarizedField>
    <summaryForeignKey>Invoice_Line__c.InvoiceId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/B2BInvoiceHelper.cls
public without sharing class B2BInvoiceHelper {
    
    @AuraEnabled(cacheable=true)
    public static List<InvoiceWrapper> getInvoices() {

        Set<String> billingEmails = new Set<String>();

        String accountId = B2BUtils.getUserAccountID();
        
        Account personAccount = [SELECT Id, Billing_Email__c, Invoice_Billing_Email__c, Business__c FROM Account WHERE Id =: accountId LIMIT 1]; 
        
        if (personAccount.Billing_Email__c != null) {
            billingEmails.add(personAccount.Billing_Email__c);
        }

        if (personAccount.Invoice_Billing_Email__c != null) {
                billingEmails.add(personAccount.Invoice_Billing_Email__c);
        }
        List<Invoice__c> invoices = new List<Invoice__c>();

        if(!billingEmails.isEmpty()) {
            invoices = [SELECT Id, Billing_Email__c, Name, Total__c, Amount_Charged__c, Period_Start_Date__c, Period_End_Date__c, Created_Date__c, Payment_Date__c, Stripe_PDF_URL__c, Stripe_Payment_URL__c, Status__c
                        FROM Invoice__c
                        WHERE Billing_Email__c IN:billingEmails AND Stripe_Payment_URL__c != null
                        ORDER BY Created_Date__c DESC
                       ];
        }

        List<InvoiceWrapper> invoiceList = new List<InvoiceWrapper>();

        for(Invoice__c invoice : invoices) {

            InvoiceWrapper iw = new InvoiceWrapper();
            iw.id = invoice.Id;
            iw.invoiceNumber = invoice.Name;
            iw.amountCharged = invoice.Amount_Charged__c;
            iw.period = String.valueOf(invoice.Period_Start_Date__c.daysBetween(invoice.Period_End_Date__c)) + ' Days';
            iw.createdDate = invoice.Created_Date__c.date();
            iw.paidDate = invoice.Payment_Date__c;
            iw.downloadLink = invoice.Stripe_PDF_URL__c;
            iw.paymentLink = invoice.Stripe_Payment_URL__c;
            iw.disablePayNow = invoice.Status__c == 'Disabled' ? true : false;
            iw.billingEmail = invoice.Billing_Email__c;

            invoiceList.add(iw);
        }
        System.debug('invoice list: ' + invoiceList[0]);
        return invoiceList;
    }
        
    public class InvoiceWrapper {

        @AuraEnabled
        public String id { get; set; }

        @AuraEnabled
        public String invoiceNumber { get; set; }

        @AuraEnabled
        public Decimal amountCharged { get; set; }

        @AuraEnabled
        public String period { get; set; }

        @AuraEnabled
        public Date createdDate { get; set; }

        @AuraEnabled
        public Date paidDate { get; set; }

        @AuraEnabled
        public String downloadLink { get; set; }

        @AuraEnabled
        public String paymentLink { get; set; }

        @AuraEnabled
        public Boolean disablePayNow { get; set; }

        @AuraEnabled
        public String billingEmail { get; set; }
    }
}