force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Assignment_Date__c</fullName>
    <label>Account Assignment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Course Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Certification Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Welcome_Kit_Parent__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>(Deprecated) Certification Kit Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships (Certification Kit Product)</relationshipLabel>
    <relationshipName>Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Welcome Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WebCart/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BWelcomeKitControllerTest.cls
@isTest
public class B2BWelcomeKitControllerTest {
    
    @TestSetup static void makeData(){
        B2BTestDataFactory.createWebStore();
        String webStoreId  = [SELECT Id FROM WebStore WHERE Name = 'TestWebStore' LIMIT 1].Id;
        String accountId = B2BTestDataFactory.createAccount();
        String contactId = B2BTestDataFactory.createContact(accountId);
        User user = B2BTestDataFactory.createCommunityUser(contactId);
        B2BTestDataFactory.createWebCart(webStoreId, accountId, user.Id);
        String productId = B2BTestDataFactory.createSetProduct();

        Account businessAccount = new Account(
            Name = 'Test Business Account'
        );
        insert businessAccount;

        Membership__c m = new Membership__c(
            Name = 'Test Membership',
            Welcome_Kit_Parent__c = productId
        );
        insert m;

        Product2 product = [SELECT Id, Membership__c FROM Product2 WHERE Name = 'Test Set Product' LIMIT 1];
        product.Membership__c = m.Id;
        update product;

        Account_Membership__c am = new Account_Membership__c(
            Membership__c = m.Id,
            Account_Id__c = accountId,
            Parent_Id__c = accountId,
            Account_Assignment_Date__c = Date.valueOf('2024-09-01'),
            Start_Date__c = Date.valueOf('2024-09-01'),
            Welcome_Kit_Status__c = 'Unclaimed',
            Status__c = 'Active'
        );
        insert am;

        Practice_Level_Membership_Assignment__c pm = new Practice_Level_Membership_Assignment__c(
            Start_Date__c = Date.valueOf('2024-09-01'),
            Welcome_Kit_Status__c = 'Unclaimed',
            Membership__c = m.Id,
            Business_Account__c = businessAccount.Id,
            Status__c = 'Active'
        );
        insert pm;
    }

    @isTest static void testGetUnclaimedKits() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        List<B2BWelcomeKitController.WelcomeKitWrapper> result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getUnclaimedKits();
        }
        Test.StopTest();
    }

    @isTest static void testGetUnclaimedKits_null() {

        String productId = [SELECT Id FROM Product2 WHERE Name = 'Test Set Product' LIMIT 1].Id;
        String cartId = [SELECT Id FROM WebCart WHERE Name = 'Test Cart' LIMIT 1].Id;
        B2BTestDataFactory.createCartDeliveryGroup(cartId, productId);

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        List<B2BWelcomeKitController.WelcomeKitWrapper> result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getUnclaimedKits();
        }
        Test.StopTest();
    }

    @isTest static void testGetUnclaimedKits_noCart() {

        WebCart cart = [SELECT Id FROM WebCart WHERE Name = 'Test Cart' LIMIT 1];
        delete cart;

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        List<B2BWelcomeKitController.WelcomeKitWrapper> result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getUnclaimedKits();
        }
        Test.StopTest();
    }

    @isTest static void testGetShippingAddress() {

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c, Business_Shipping_Address__Street__s, Business_Shipping_Address__City__s, Business_Shipping_Address__StateCode__s, Business_Shipping_Address__PostalCode__s, Business_Shipping_Address__CountryCode__s
                           FROM Account 
                           WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        account.Business_Shipping_Address__Street__s = '2000 Auburn Street';
        account.Business_Shipping_Address__City__s = 'Beachwood';
        account.Business_Shipping_Address__StateCode__s = 'OH';
        account.Business_Shipping_Address__PostalCode__s = '44122';
        account.Business_Shipping_Address__CountryCode__s = 'US';
        update account;

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        B2BWelcomeKitController.AddressWrapper result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getShippingAddress();
        }
        Test.StopTest();
    }

    @isTest static void testGetShippingAddress_null() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        B2BWelcomeKitController.AddressWrapper result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getShippingAddress();
        }
        Test.StopTest();
    }

    @isTest static void testAddWelcomeKitToCart() {

        String productId = [SELECT Id FROM Product2 WHERE Name = 'Test Set Product' LIMIT 1].Id;
        String cartId = [SELECT Id FROM WebCart WHERE Name = 'Test Cart' LIMIT 1].Id;
        B2BTestDataFactory.createCartDeliveryGroup(cartId, productId);

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Test.StartTest();
        System.runAs(user) {
            B2BWelcomeKitController.addWelcomeKitToCart(productId);
        }
        Test.StopTest();
    }

    @isTest static void testSaveShippingAddress() {

        String productId = [SELECT Id FROM Product2 WHERE Name = 'Test Set Product' LIMIT 1].Id;
        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        update account;

        B2BWelcomeKitController.AddressWrapper address = new B2BWelcomeKitController.AddressWrapper();
        address.street = '2000 Auburn Dr';
        address.city = 'Beachwood';
        address.state = 'OH';
        address.postalCode = '44122';
        address.country = 'US';

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Test.StartTest();
        System.runAs(user) {
            B2BWelcomeKitController.saveShippingAddress(address);
        }
        Test.StopTest();
    }

    @isTest static void testGetUnclaimedPracticeLevelKits() {

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        update account;

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        List<Practice_Level_Membership_Assignment__c> result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getUnclaimedPracticeLevelKits();
        }
        Test.StopTest();
    }

    @isTest static void testGetUnclaimedPracticeLevelKits_null() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        List<Practice_Level_Membership_Assignment__c> result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.getUnclaimedPracticeLevelKits();
        }
        Test.StopTest();
    }

    @isTest static void testCreateOrderSummary() {

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        update account;

        String membershipId = [SELECT Id FROM Membership__c WHERE Name = 'Test Membership' LIMIT 1].Id;
        List<String> membershipIds = new List<String>();
        membershipIds.add(membershipId);

        B2BWelcomeKitController.AddressWrapper address = new B2BWelcomeKitController.AddressWrapper();
        address.street = '2000 Auburn Dr';
        address.city = 'Beachwood';
        address.state = 'OH';
        address.postalCode = '44122';
        address.country = 'US';

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.createOrderSummary(membershipIds, address);
        }
        Test.StopTest();
    }

    @isTest static void testCreateOrderSummary_withShippingProd() {
        B2BTestDataFactory.createShippingProduct();

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        update account;

        String membershipId = [SELECT Id FROM Membership__c WHERE Name = 'Test Membership' LIMIT 1].Id;
        List<String> membershipIds = new List<String>();
        membershipIds.add(membershipId);

        B2BWelcomeKitController.AddressWrapper address = new B2BWelcomeKitController.AddressWrapper();
        address.street = '2000 Auburn Dr';
        address.city = 'Beachwood';
        address.state = 'OH';
        address.postalCode = '44122';
        address.country = 'US';

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.createOrderSummary(membershipIds, address);
        }
        Test.StopTest();
    }

    @isTest static void testCreateOrderSummary_withODM() {
        B2BTestDataFactory.createShippingProduct();
        String productId = [SELECT Id FROM Product2 WHERE Name = 'Delivery Charge' LIMIT 1].Id;
        B2BTestDataFactory.createOrderDeliveryMethod(productId);

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];

        Account account = [SELECT Id, Business__c FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.Business__c = businessAccount.Id;
        update account;

        String membershipId = [SELECT Id FROM Membership__c WHERE Name = 'Test Membership' LIMIT 1].Id;
        List<String> membershipIds = new List<String>();
        membershipIds.add(membershipId);

        B2BWelcomeKitController.AddressWrapper address = new B2BWelcomeKitController.AddressWrapper();
        address.street = '2000 Auburn Dr';
        address.city = 'Beachwood';
        address.state = 'OH';
        address.postalCode = '44122';
        address.country = 'US';

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Boolean result;
        Test.StartTest();
        System.runAs(user) {
            result = B2BWelcomeKitController.createOrderSummary(membershipIds, address);
        }
        Test.StopTest();
    }

    @isTest static void testUpdatePracticeCertificationKitStatus() {

        Account businessAccount = [SELECT Id FROM Account WHERE Name = 'Test Business Account' LIMIT 1];
        Id productId = [SELECT Id FROM Product2 WHERE Name = 'Test Set Product' LIMIT 1].Id;
        List<Id> productIds = new List<Id>();
        productIds.add(productId);

        Test.StartTest();
        B2BWelcomeKitController.updatePracticeCertificationKitStatus(businessAccount.Id, productIds, null);
        Test.StopTest();
    }
}