force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <label>StripeCustomerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Previous Practice Membership Assignment used for renewal</description>
    <inlineHelpText>Previous Practice Membership Assignment used for renewal</inlineHelpText>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Order Products</relationshipLabel>
    <relationshipName>Order_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BRenewalController.cls
public class B2BRenewalController {
    public static void handlePLMA(Account record) {
        
        List<B2BPracticeLevelRenewalsWrapper.PracticeLevelMembershipAssignment> plmaList = B2BPracticeLevelRenewalsService.getPracticeLevelMembershipAssignments(record.Id);
        if (plmaList == null || plmaList.isEmpty()) {
            return;
        }

        Date nearestRenewalDate = plmaList[0].expirationDate;
        B2BPracticeLevelRenewalsWrapper.BusinessAccount businessAccount = B2BPracticeLevelRenewalsService.getBusinessAccount(record, nearestRenewalDate);
        B2BPracticeLevelRenewalsWrapper.Order order = B2BPracticeLevelRenewalsService.createOrder(businessAccount);
        B2BPracticeLevelRenewalsService.createOrderItems(plmaList, order);
    }

    public static void handleILMA(Account record) {

        List<B2BIndividualLevelRenewalsWrapper.IndividualLevelMembershipAssignment> ilmaList = B2BIndividualLevelRenewalsService.getIndividualLevelMembershipAssignments(record.Id);
        if (ilmaList == null || ilmaList.isEmpty()) {
            return;
        }

        Date nearestRenewalDate = ilmaList[0].expirationDate;
        B2BIndividualLevelRenewalsWrapper.ParentAccount parentAccount = B2BIndividualLevelRenewalsService.getParentAccount(record, nearestRenewalDate);
    
        B2BIndividualLevelRenewalsWrapper.Order order;
        order = B2BIndividualLevelRenewalsService.getExistingOrder(record);
        if(order == null) {

            order = B2BIndividualLevelRenewalsService.createOrder(parentAccount);
        }
        
        B2BIndividualLevelRenewalsService.createOrderItems(ilmaList, order);
    }

    public static void handleInvoiceCreation(Order record) {
        
        String orderId = record.Id;
        String accountId = record.Account.Id;

        //Get OrderItems of type 'Order Product'
        List<OrderItem> orderItems = [
            SELECT Id, OrderId, Product2.Membership__r.Id
            FROM OrderItem 
            WHERE OrderId = :orderId AND Type = 'Order Product'
        ];

        //Collect MembershipIds of each order item
        Set<Id> membershipIds = new Set<Id>();
        for (OrderItem item : orderItems) {
            if (item.Product2.Membership__r.Id != null) {
                membershipIds.add(item.Product2.Membership__r.Id);
            }
        }
        
        if (accountId != null) {
            Account account = [SELECT Id, Business__c FROM Account WHERE Id = :accountId];
            if (account.Business__c != null) {
                accountId = account.Business__c;
            }

            Set<Id> activeMembershipIds = new Set<Id>();
            if(!membershipIds.isEmpty()) {

                //Check if Individual Memberships are Active to Renew
                List<Account_Membership__c> activeIndividualMemberships = [
                    SELECT Id, Membership__c, Status__c, Account_Id__c
                    FROM Account_Membership__c 
                    WHERE Membership__c IN :membershipIds 
                    AND Parent_Id__c = :accountId
                    AND Status__c = 'Active'
                    ORDER BY CreatedDate Desc NULLS LAST
                ];

                if(activeIndividualMemberships.size() > 0) {
                    for(Account_Membership__c am : activeIndividualMemberships) {
                        activeMembershipIds.add(am.Membership__c);
                    }
                }

                //Check if Practice Memberships are Active to Renew
                List<Practice_Level_Membership_Assignment__c> activePracticeMemberships = [
                    SELECT Id, Membership__c, Status__c 
                    FROM Practice_Level_Membership_Assignment__c 
                    WHERE Membership__c IN :membershipIds 
                    AND Business_Account__c = :accountId
                    AND Status__c = 'Active'
                    ORDER BY CreatedDate Desc NULLS LAST
                ];

                if(activePracticeMemberships.size() > 0) {
                    for(Practice_Level_Membership_Assignment__c pm : activePracticeMemberships) {
                        activeMembershipIds.add(pm.Membership__c);
                    }
                }
            }

            //If there are no active memberships delete the orderitems with the corresponding membershipids
            List<OrderItem> orderItemsToDelete = new List<OrderItem>();

            if(!activeMembershipIds.isEmpty()) {
                for (OrderItem item : orderItems) {
                    if(!activeMembershipIds.contains(item.Product2.Membership__r.Id)) {
                        orderItemsToDelete.add(item);
                    }
                }

                if(!orderItemsToDelete.isEmpty()) {
                    delete orderItemsToDelete;
                }

                String stripeInvoiceId = B2BStripePaymentController.createInvoiceByOrderId(orderId, record.Account.StripeCustomerId__c, record.Account.Id);
            }
        }
    }
}