force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/IndividualLevelRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>IndividualLevelRenewalDate__c</fullName>
    <label>IndividualLevelRenewalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/PracticeLevelRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>PracticeLevelRenewalDate__c</fullName>
    <label>PracticeLevelRenewalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/B2BCalculateRenewalDatesScheduler.cls
global class B2BCalculateRenewalDatesScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {

        String query = 'SELECT Id, IndividualLevelRenewalDate__c, PracticeLevelRenewalDate__c ' +
                       'FROM Account ' + 
                       'WHERE RecordTypeId = :businessRecordTypeId ' +
                       'OR (RecordTypeId = :personRecordTypeId AND Business__c = null)';

        Integer batchSize = Integer.valueOf(System.Label.B2B_Calculate_Renewal_Dates_Batch_Size);

        B2BCalculateRenewalDatesBatch b = new B2BCalculateRenewalDatesBatch(query); 
        Database.executeBatch(b, batchSize);
    }
}