force-app/main/default/objects/Account/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Business</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Members</relationshipLabel>
    <relationshipName>Members</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Directory_Opt_In__c.field-meta.xml
<CustomField>
    <fullName>Directory_Opt_In__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Directory Opt-In</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Certified Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Practice Manager</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>CSR</fullName>
            </value>
            <value>
                <fullName>Kennel Attendant/Technician</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Assistant Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Technician Program</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Behavioral Consultant</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Dog Walker</fullName>
            </value>
            <value>
                <fullName>Other (Veterinary)</fullName>
            </value>
            <value>
                <fullName>Other (Non-Veterinary)</fullName>
            </value>
            <value>
                <fullName>Team Admin</fullName>
                <isActive>false</isActive>
                <label>Team Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Assigned_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Account_Name__c</fullName>
    <formula>Account_Id__r.FirstName + &quot; &quot; + Account_Id__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Assigned Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/directoryMembersController.cls
public with sharing class directoryMembersController {
    @AuraEnabled
    public static List<Account> getChildAccounts(String parentId) {
        return [SELECT Name, Job_Title__c
        //(SELECT Assigned_Account_Name__c FROM Account_Memberships__r  WHERE Certified__c = true AND Status__c = 'Active')  
        FROM Account WHERE Business__c = :parentId 
        AND Directory_Opt_In__c = true
        AND Id IN (SELECT Account_Id__c FROM Account_Membership__c WHERE Certified__c = true 
        AND Status__c = 'Active') ];
    }
}