force-app/main/default/objects/Account/fields/CE_Credits__c.field-meta.xml
<CustomField>
    <fullName>CE_Credits__c</fullName>
    <label>CE Credits</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX LMS User</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification_Course__c/Certification_Course__c.object-meta.xml
<CustomObject>
    <label>Certification Course</label>
    <nameField>
        <displayFormat>CC-{0000}</displayFormat>
        <label>Certification Course Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certification Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Certification_Course__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Certification Courses</relationshipLabel>
    <relationshipName>Certification_Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Certification_Course__c/fields/SX_Course__c.field-meta.xml
<CustomField>
    <fullName>SX_Course__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>SX Course</label>
    <referenceTo>SX_Courses__c</referenceTo>
    <relationshipLabel>Certification Courses</relationshipLabel>
    <relationshipName>Certification_Courses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/CE_Credits__c.field-meta.xml
<CustomField>
    <fullName>CE_Credits__c</fullName>
    <label>CE Credits</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <inlineHelpText>Select membership(s) an individual has</inlineHelpText>
    <label>Membership</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinary</fullName>
            </value>
            <value>
                <fullName>Animal Trainer</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Boarding &amp; Daycare</fullName>
            </value>
            <value>
                <fullName>Shelter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>SX_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX Enrollment</label>
    <referenceTo>SX_Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX LMS User</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_User_Id__c.field-meta.xml
<CustomField>
    <fullName>SX_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>SX User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/CE_Hours__c.field-meta.xml
<CustomField>
    <fullName>CE_Hours__c</fullName>
    <label>CE Hours</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>SX Courses</relationshipLabel>
    <relationshipName>SX_Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/SX_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Tracks the Schoox LMS course enrollment for each learner along with key statistics.</description>
    <label>SX Enrollment</label>
    <nameField>
        <label>SX Enrollment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Enrollment__c/fields/Account_Membership__c.field-meta.xml
<CustomField>
    <fullName>Account_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Membership</label>
    <referenceTo>Account_Membership__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/CE_Credits__c.field-meta.xml
<CustomField>
    <fullName>CE_Credits__c</fullName>
    <formula>SX_Course__r.CE_Hours__c</formula>
    <label>CE Credits</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Certification_Course__c.field-meta.xml
<CustomField>
    <fullName>Certification_Course__c</fullName>
    <formula>NOT(ISBLANK(SX_Course__r.Membership__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Certification Course</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SF_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <label>Student ID</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SX_Course__c.field-meta.xml
<CustomField>
    <fullName>SX_Course__c</fullName>
    <label>Course</label>
    <referenceTo>SX_Courses__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SX_percent_Completed__c.field-meta.xml
<CustomField>
    <fullName>SX_percent_Completed__c</fullName>
    <label>% Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX LMS Users</relationshipLabel>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <label>SX LMS User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FFEnrollmentTriggerTest.cls
@isTest
public class FFEnrollmentTriggerTest {
    @isTest
    static void testTriggerFires() {
        // Create a Person Account
        Account acc = new Account(
            RecordTypeId = [SELECT Id FROM RecordType WHERE SObjectType='Account' AND IsPersonType=true LIMIT 1].Id,
            LastName = 'Test Person',
            FirstName = 'Trigger'
        );
        insert acc;

        // Create Contact (auto-created for Person Account)
        Contact con = [SELECT Id, AccountId FROM Contact WHERE AccountId = :acc.Id LIMIT 1];

        // Create a Membership
        Membership__c membership = new Membership__c(Name = 'Vet Pro');
        insert membership;

        // Create Account_Membership__c
        Account_Membership__c acctMembership = new Account_Membership__c(
            Account_Id__c = acc.Id,
            Membership__c = membership.Id,
            Certified__c = false
        );
        insert acctMembership;

        // Create Course
        SX_Courses__c course = new SX_Courses__c(
            Name = 'Course A',
            Membership__c = membership.Id,
            CE_Hours__c = 5
        );
        insert course;

        // Map Course → Membership through Certification_Course__c
        Certification_Course__c cc = new Certification_Course__c(
            SX_Course__c = course.Id,
            Membership__c = membership.Id
        );
        insert cc;

        // Create LMS User
        SX_LMS_User__c lmsUser = new SX_LMS_User__c(
            SF_Contact__c = con.Id,
            SX_User_ID__c = 'test-user-002',
            SX_Active_User__c = true
        );
        insert lmsUser;

        // Create Enrollment that meets trigger conditions
        SX_Enrollment__c enrollment = new SX_Enrollment__c(
            Name = 'Enroll A',
            SF_Contact_Lookup__c = con.Id,
            SX_Course__c = course.Id,
            SX_percent_Completed__c = 100,
            Student_ID__c = lmsUser.Id
        );
        insert enrollment; // 🚀 fires the trigger

        // Verify Account_Membership__c updated
        Account_Membership__c updated = [
            SELECT Certified__c
            FROM Account_Membership__c
            WHERE Id = :acctMembership.Id
        ];
        System.assertEquals(true, updated.Certified__c, 'Account_Membership__c should be marked Certified');

        // Debug enrollments to see if multiple exist
        List<SX_Enrollment__c> enrollments = [
            SELECT Id, CE_Credits__c, SX_Course__c
            FROM SX_Enrollment__c
            WHERE SF_Contact_Lookup__c = :con.Id
        ];
        System.debug('Enrollments found: ' + enrollments);

        // Verify only 1 enrollment exists for this test
        System.assertEquals(1, enrollments.size(), 'Expected only 1 enrollment in this test');
        System.assertEquals(5, enrollments[0].CE_Credits__c, 'Enrollment should have 5 CE credits');

        // Verify CE credits rolled up to Account
        Account refreshedAcc = [SELECT CE_Credits__c FROM Account WHERE Id = :acc.Id];
        System.debug('Account CE_Credits__c: ' + refreshedAcc.CE_Credits__c);
        System.assertEquals(5, refreshedAcc.CE_Credits__c, 'Account CE_Credits__c should equal enrollment credits');
    }
}