force-app/main/default/objects/Account/fields/Historical_Primary_Group__c.field-meta.xml
<CustomField>
    <fullName>Historical_Primary_Group__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Historical Primary Group</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Historical_Account_Group__c/Historical_Account_Group__c.object-meta.xml
<CustomObject>
    <label>Historical Account Group Member</label>
    <nameField>
        <label>Historical Account Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Historical Account Group Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/B2BHistoricalGroupsBatchTest.cls
@isTest
public class B2BHistoricalGroupsBatchTest {

    @isTest
    static void runBatch() {
        Id businessRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND Name = 'Business Account' LIMIT 1].Id;
        Id personRtId = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND IsPersonType = true LIMIT 1].Id;

        Account biz = new Account(
            Name = 'Biz',
            RecordTypeId = businessRtId,
            Historical_Primary_Group__c = true,
            Original_System_ID__c = 'B001'
        );
        insert biz;

        Account person = new Account(
            FirstName = 'Test',
            LastName = 'Person',
            RecordTypeId = personRtId,
            Original_System_ID__c = 'U001'
        );
        insert person;

        Historical_Account_Group__c match = new Historical_Account_Group__c(
            Name = 'Match',
            Group_Id__c = 'B001',
            User_Id__c = 'U001'
        );

        Historical_Account_Group__c noBiz = new Historical_Account_Group__c(
            Name = 'NoBiz',
            Group_Id__c = 'B404',
            User_Id__c = 'U001'
        );

        Historical_Account_Group__c noUser = new Historical_Account_Group__c(
            Name = 'NoUser',
            Group_Id__c = 'B001',
            User_Id__c = 'U404'
        );

        insert new List<Historical_Account_Group__c>{ match, noBiz, noUser };

        Test.startTest();
        Database.executeBatch(new B2BProcessHistoricalAccountGroupsBatch(), 200);
        Test.stopTest();
    }
}