force-app/main/default/objects/Account/fields/Job_Title__c.field-meta.xml
<CustomField>
    <fullName>Job_Title__c</fullName>
    <label>Job Title</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinarian</fullName>
            </value>
            <value>
                <fullName>Certified Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Practice Manager</fullName>
            </value>
            <value>
                <fullName>Support Staff</fullName>
            </value>
            <value>
                <fullName>CSR</fullName>
            </value>
            <value>
                <fullName>Kennel Attendant/Technician</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Assistant Program</fullName>
            </value>
            <value>
                <fullName>Faculty - Veterinary Technician Program</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Assistant</fullName>
            </value>
            <value>
                <fullName>Student - Veterinary Technician</fullName>
            </value>
            <value>
                <fullName>Behavioral Consultant</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Dog Walker</fullName>
            </value>
            <value>
                <fullName>Other (Veterinary)</fullName>
            </value>
            <value>
                <fullName>Other (Non-Veterinary)</fullName>
            </value>
            <value>
                <fullName>Team Admin</fullName>
                <isActive>false</isActive>
                <label>Team Admin</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/License_Number__c.field-meta.xml
<CustomField>
    <fullName>License_Number__c</fullName>
    <inlineHelpText>This field is intended for veterinarians and veterinary technicians/nurses.</inlineHelpText>
    <label>License Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Trainer_CCPDT_Number__c.field-meta.xml
<CustomField>
    <fullName>Trainer_CCPDT_Number__c</fullName>
    <inlineHelpText>This field is intended for Certified Professional Dog Trainers.</inlineHelpText>
    <label>Trainer CCPDT Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/B2BEditAccountDetailsController.cls
public without sharing class B2BEditAccountDetailsController {
    
    @AuraEnabled
    public static void updateAccountRecord(Map<String, String> accountDetails){
        try {
            String accountId = accountDetails.get('Id');

            List<Account> account = [SELECT Id, License_Number__c, Trainer_CCPDT_Number__c, Job_Title__c
                                     FROM Account
                                     WHERE Id = :accountId];

            if(account.size() > 0) {
                account[0].License_Number__c = accountDetails.get('licenseNumber');
                account[0].Trainer_CCPDT_Number__c = accountDetails.get('ccpdtNumber');
                account[0].Job_Title__c = accountDetails.get('jobTitle');

                update account[0];
            }
        } 
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BEditAccountDetailsController', 'updateAccountRecord');
        }
    }
}