force-app/main/default/objects/Account/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/B2B_Custom_Exception__c/B2B_Custom_Exception__c.object-meta.xml
<CustomObject>
    <label>B2B Custom Exception</label>
    <nameField>
        <label>B2B Custom Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>B2B Custom Exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Membership_PLMA__mdt/Historical_Membership_PLMA__mdt.object-meta.xml
<CustomObject>
    <label>Historical Membership PLMA</label>
    <pluralLabel>Historical Membership PLMAS</pluralLabel>
</CustomObject>

force-app/main/default/objects/Historical_Membership_PLMA__mdt/fields/Membership_Id__c.field-meta.xml
<CustomField>
    <fullName>Membership_Id__c</fullName>
    <label>Membership Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/Historical_PLMA__c.object-meta.xml
<CustomObject>
    <label>Historical PLMA</label>
    <nameField>
        <displayFormat>PLMA-{0000}</displayFormat>
        <label>Historical PLMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical PLMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_PLMA__c/fields/Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Admin_Id__c</fullName>
    <label>Admin Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/B2B_Custom_Exception__c.field-meta.xml
<CustomField>
    <fullName>B2B_Custom_Exception__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>B2B Custom Exception</label>
    <referenceTo>B2B_Custom_Exception__c</referenceTo>
    <relationshipLabel>Historical PLMAS</relationshipLabel>
    <relationshipName>Historical_PLMAS</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Cert_Date__c.field-meta.xml
<CustomField>
    <fullName>Cert_Date__c</fullName>
    <label>Cert Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Cert_Status__c.field-meta.xml
<CustomField>
    <fullName>Cert_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cert Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Data_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Status__c</fullName>
    <label>Data Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VPC-ER</fullName>
            </value>
            <value>
                <fullName>VPC-GP</fullName>
            </value>
            <value>
                <fullName>VPC-HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/PLMA_Status__c.field-meta.xml
<CustomField>
    <fullName>PLMA_Status__c</fullName>
    <formula>CASE(
TEXT(Status__c),
 &apos;active&apos;, &apos;Active&apos;, 
&apos;expired&apos;,&apos;Complete&apos;,
&apos;cancelled&apos;,&apos;Voided&apos;,
TEXT(Status__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLMA Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>expired</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>(Deprecated) Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinary</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Boarding &amp; Daycare</fullName>
            </value>
            <value>
                <fullName>Shelter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Certification_Date__c.field-meta.xml
<CustomField>
    <fullName>Certification_Date__c</fullName>
    <label>Certification Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Certified__c.field-meta.xml
<CustomField>
    <fullName>Certified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Certified</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Historical_PLMA__c.field-meta.xml
<CustomField>
    <fullName>Historical_PLMA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical PLMA</label>
    <referenceTo>Historical_PLMA__c</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments</relationshipLabel>
    <relationshipName>Practice_Level_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Historical_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Historical_Start_Date__c</fullName>
    <label>Historical Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Need_Historical_Review__c.field-meta.xml
<CustomField>
    <fullName>Need_Historical_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Need Historical Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Purchaser__c.field-meta.xml
<CustomField>
    <fullName>Purchaser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchaser</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Welcome Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BCreatePracticeHistoricalMembership.cls
/**
* @File Name : B2BCreatePracticeHistoricalMembership.cls
* @Description : Create PLMS Records from Historical PLMA Records
* Test class :B2BCreatePLMATest
* @Author : Meenakshi Jain@Stack Intelligence
* @Created : June 2025
*/
public class B2BCreatePracticeHistoricalMembership implements Database.Batchable<sObject>, Database.Stateful {
    //variable
    String query;
    //constructor
    public B2BCreatePracticeHistoricalMembership() { }
    public B2BCreatePracticeHistoricalMembership(String query){
        this.query = query;
    }
    
    //start of batch
    public List<Historical_PLMA__c> start(Database.BatchableContext BC) {
        List<Historical_PLMA__c> historicalList = new List<Historical_PLMA__c>();

        historicalList = String.isNotBlank(query) ? 
            Database.query(query) 
            :[SELECT Id,Cert_Date__c,Cert_Status__c,Admin_Id__c,PLMA_Status__c,
              End_Date__c,Group_ID__c,Membership_Type__c,Start_Date__c,Status__c
              FROM Historical_PLMA__c
              WHERE Data_Status__c = 'Pending'];
                  return historicalList;
    }
    
    //execute of batch
    public void execute(Database.BatchableContext bc, List<Historical_PLMA__c> scope) {
        processRecords(scope);
    }
    //finish of batch
    public void finish(Database.BatchableContext bc) {
        System.debug('Finish method called');
    }
    
    //Process Records
    public static void processRecords( List<Historical_PLMA__c> scope){
        try{
            System.debug('Execute method - Scope size: ' + scope.size());
            Set<String> groupIdSet = new Set<String>();
            Map<String,B2B_Custom_Exception__c> b2bCustomExceptionList = new Map<String,B2B_Custom_Exception__c>();
            
            for(Historical_PLMA__c historicalPlma : scope){
                if(String.isNotBlank(historicalPlma.Group_ID__c)){
                    groupIdSet.add(historicalPlma.Group_ID__c);
                }else{
                    
                    b2bCustomExceptionList.put(historicalPlma.Id,
                                               B2BHandleCustomException.logExceptionWithoutInsert(
                                                   new B2BCreateHistoricalMembershipsBatch.HistoricalMembershipException('Group Id is Blank'),
                                                   'Historical Memberships PLMA',
                                                   'PLMA Membership Creation'
                                               ));
                }
                
                if(String.isNotBlank(historicalPlma.Admin_Id__c)){
                    groupIdSet.add(historicalPlma.Admin_Id__c);
                }else{
                    
                    b2bCustomExceptionList.put(historicalPlma.Id,
                                               B2BHandleCustomException.logExceptionWithoutInsert(
                                                   new B2BCreateHistoricalMembershipsBatch.HistoricalMembershipException('Admin Id is Blank'),
                                                   'Historical Memberships PLMA',
                                                   'PLMA Membership Creation'
                                               ));
                }
            }
            
            
            if(!groupIdSet.isEmpty()){
                Map<String,Id> groupVsAccountIdMap = new Map<String,Id>();
                List<Account> accountList = [SELECT Id,Original_System_ID__c 
                                             FROM account WHERE Original_System_ID__c IN: groupIdSet];
                for(Account account : accountList){
                    groupVsAccountIdMap.put(account.Original_System_ID__c,account.Id);
                }
                List<Practice_Level_Membership_Assignment__c> practiceMembershipList = new List<Practice_Level_Membership_Assignment__c>();
                
                Map<String,String> historicalMetadata = getHistoricalMetadata();
                for(Historical_PLMA__c historicalPlma : scope){
                    String message = '';
                    if(!groupVsAccountIdMap.containsKey(historicalPlma.Group_ID__c))
                        message = 'No Account Exist for the Group Id - '+historicalPlma.Group_ID__c;
                    else if(!groupVsAccountIdMap.containsKey(historicalPlma.Admin_Id__c))
                        message = 'No Account Exist for the Admin Id - '+historicalPlma.Admin_Id__c;                        
                    else if(!historicalMetadata.containsKey(historicalPlma.Membership_Type__c))
                        message = 'Membership does not Exist for associated Membership type on Historical PLMA';
                    
                    if(String.isNotBlank(message)){
                        b2bCustomExceptionList.put(historicalPlma.Id,
                                                   B2BHandleCustomException.logExceptionWithoutInsert(
                                                       new B2BCreateHistoricalMembershipsBatch.HistoricalMembershipException(message),
                                                       'Historical Memberships PLMA',
                                                       'PLMA Membership Creation'
                                                   ));
                    }else{
                        practiceMembershipList.add(
                            new Practice_Level_Membership_Assignment__c(
                                Business_Account__c = groupVsAccountIdMap.get(historicalPlma.Group_ID__c),
                                Status__c = historicalPlma.PLMA_Status__c,
                                Historical_Start_Date__c = historicalPlma.Start_Date__c,
                                Start_Date__c = historicalPlma.End_Date__c != null ?
                                historicalPlma.End_Date__c.addYears(-1) : null,
                                Certification_Date__c  =historicalPlma.Cert_Date__c,
                                Certified__c = historicalPlma.Cert_Status__c,
                                Membership__c = historicalMetadata.get(historicalPlma.Membership_Type__c),
                                Purchaser__c = groupVsAccountIdMap.get(historicalPlma.Admin_Id__c),
                                Historical_PLMA__c = historicalPlma.Id,
                                Need_Historical_Review__c = true,
                                Welcome_Kit_Status__c = 'Unavailable'
                            ));
                    }
                }
                if(!practiceMembershipList.isEmpty()){
                    List<Database.SaveResult> saveResultList = Database.insert(practiceMembershipList,false);
                    Integer i = 0;
                    for(Database.SaveResult sr : saveResultList){
                        if (!sr.isSuccess()) {
                            for(Database.Error err : sr.getErrors()) {
                                System.debug('The following error has occurred.');                    
                                System.debug(err.getStatusCode() + ': ' + err.getMessage());
                                b2bCustomExceptionList.put(practiceMembershipList[i].Historical_PLMA__c,
                                                           B2BHandleCustomException.logExceptionWithoutInsert(
                                                               new B2BCreateHistoricalMembershipsBatch.HistoricalMembershipException(err.getStatusCode() + ': ' + err.getMessage()),
                                                               'Historical Memberships PLMA',
                                                               'PLMA Membership Creation'
                                                           ));
                            }
                        }
                        i++;
                        
                    }
                    
                }
                
            }
            if(!b2bCustomExceptionList.isEmpty()){
                insert b2bCustomExceptionList.values();
            }
            for(Historical_PLMA__c historicalPlma : scope){
                
                if(b2bCustomExceptionList.containsKey(historicalPlma.Id)){
                    historicalPlma.B2B_Custom_Exception__c = b2bCustomExceptionList.get(historicalPlma.Id).Id;
                }
                historicalPlma.Data_Status__c = b2bCustomExceptionList.containsKey(historicalPlma.Id) ?
                    'Unsuccessful' : 'Successful';
            }
            update scope;
        }catch (Exception e) {
            System.debug('Batch-level exception: ' + e.getMessage());
            B2BHandleCustomException.LogException(e, 'Historical PLMA Memberships', 'PLMA Membership Creation - Batch Level Failure');
        }
    }
    
    //get historical metadata
    public static Map<String,String> getHistoricalMetadata(){
        Map<String,Historical_Membership_PLMA__mdt> historicalMap = Historical_Membership_PLMA__mdt.getAll();
        Map<String,String> responseMap = new Map<String,String>();
        for(Historical_Membership_PLMA__mdt historical : historicalMap.values()){
            responseMap.put(historical.Label,historical.Membership_Id__c);
        }
        return responseMap;
    }
    
    
    
}