force-app/main/default/objects/Account/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/Provisioned_to_B2B_Store__c.field-meta.xml
<CustomField>
    <fullName>Provisioned_to_B2B_Store__c</fullName>
    <label>Provisioned to B2B Store</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
            <value>
                <fullName>User Exist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BProvisioningBatchTest.cls
@isTest
private class B2BProvisioningBatchTest {

    @isTest
    static void runBatch_withFactoryPersonAccounts() {
        Id personAccId = B2BTestDataFactory.createPersonAccount();

        Contact con = [SELECT Id FROM Contact WHERE AccountId = :personAccId LIMIT 1];
        Account acc = [SELECT Id, PersonEmail FROM Account WHERE Id = :personAccId];

        acc.PersonEmail = 'provision-' + System.currentTimeMillis() + '@test.com';
        acc.Provisioned_to_B2B_Store__c = 'Pending';
        acc.Original_System_ID__c = 'Test123';
        update acc;

        Test.startTest();
        Database.executeBatch(new B2BProvisioningBatch(), 200);
        Test.stopTest();
    }

    @isTest
    static void runBatch_withFactoryPersonAccounts_unsuccessfull() {
        Id personAccId = B2BTestDataFactory.createPersonAccount();

        Contact con = [SELECT Id FROM Contact WHERE AccountId = :personAccId LIMIT 1];
        Account acc = [SELECT Id, PersonEmail FROM Account WHERE Id = :personAccId];

        acc.Provisioned_to_B2B_Store__c = 'Pending';
        acc.Original_System_ID__c = 'Test12345';
        update acc;

        Test.startTest();
        Database.executeBatch(new B2BProvisioningBatch(), 200);
        Test.stopTest();
    }
}