force-app/main/default/objects/Account/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/Historical_PLMA__c.object-meta.xml
<CustomObject>
    <label>Historical PLMA</label>
    <nameField>
        <displayFormat>PLMA-{0000}</displayFormat>
        <label>Historical PLMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical PLMAS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_PLMA__c/fields/Admin_Id__c.field-meta.xml
<CustomField>
    <fullName>Admin_Id__c</fullName>
    <label>Admin Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Cert_Date__c.field-meta.xml
<CustomField>
    <fullName>Cert_Date__c</fullName>
    <label>Cert Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Cert_Status__c.field-meta.xml
<CustomField>
    <fullName>Cert_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cert Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Data_Status__c.field-meta.xml
<CustomField>
    <fullName>Data_Status__c</fullName>
    <label>Data Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Successful</fullName>
            </value>
            <value>
                <fullName>Unsuccessful</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Group_ID__c.field-meta.xml
<CustomField>
    <fullName>Group_ID__c</fullName>
    <label>Group ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VPC-ER</fullName>
            </value>
            <value>
                <fullName>VPC-GP</fullName>
            </value>
            <value>
                <fullName>VPC-HC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/PLMA_Status__c.field-meta.xml
<CustomField>
    <fullName>PLMA_Status__c</fullName>
    <formula>CASE(
TEXT(Status__c),
 &apos;active&apos;, &apos;Active&apos;, 
&apos;expired&apos;,&apos;Complete&apos;,
&apos;cancelled&apos;,&apos;Voided&apos;,
TEXT(Status__c)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PLMA Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_PLMA__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>active</fullName>
            </value>
            <value>
                <fullName>expired</fullName>
            </value>
            <value>
                <fullName>cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Membership_Type__c.field-meta.xml
<CustomField>
    <fullName>Membership_Type__c</fullName>
    <label>(Deprecated) Membership Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veterinary</fullName>
            </value>
            <value>
                <fullName>Groomer</fullName>
            </value>
            <value>
                <fullName>Trainer</fullName>
            </value>
            <value>
                <fullName>Pet Sitter</fullName>
            </value>
            <value>
                <fullName>Boarding &amp; Daycare</fullName>
            </value>
            <value>
                <fullName>Shelter</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/classes/B2BCreatePLMATest.cls
@isTest
public class B2BCreatePLMATest {
    @testSetup
    public static void createData(){
        Id recordTypeId;
        if (Schema.SObjectType.Account.getRecordTypeInfosByName().containsKey('Person Account')) {
            recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        }
        
        Account personAccount = new Account(
            FirstName = 'Jane',
            LastName = 'Doe',
            PersonEmail = 'jane@example.com',
            Original_System_ID__c = '123489'
        );
        if (recordTypeId != null) {
            personAccount.RecordTypeId = recordTypeId;
        }
        insert personAccount;
        
        Membership__c individualMembership = new Membership__c(
            Name = 'Veterinary Practice Certification - ER/Urgent Care Membership'
        );
        insert individualMembership;
        
        
        
    }
    @isTest
    public static void testBatch(){
        Historical_PLMA__c historical = new Historical_PLMA__c(
            Cert_Date__c = System.today() + 10,
            Cert_Status__c = true,
            Admin_Id__c = '123489',
            End_Date__c =System.today() + 30,
            Group_ID__c = '123489',
            Start_Date__c = system.today()-30,
            Status__c = 'active',
            Membership_Type__c = 'VPC-ER',
            Data_Status__c = 'Pending'
        );
        insert historical;
        Test.startTest();
        Database.executeBatch(new B2BCreatePracticeHistoricalMembership());
        Test.stopTest();
        Historical_PLMA__c historical1 = [SELECT Id,Data_Status__c FROM Historical_PLMA__c LIMIT 1];
    }
    
    @isTest
    public static void testGroupBlank(){
        Historical_PLMA__c historical = new Historical_PLMA__c(
            Cert_Date__c = System.today() + 10,
            Cert_Status__c = true,
            Admin_Id__c = '123489',
            End_Date__c =System.today() + 30,
            Start_Date__c = system.today()-30,
            Status__c = 'active',
            Membership_Type__c = 'VPC-ER',
            Data_Status__c = 'Pending'
        );
        insert historical;
        Test.startTest();
        String qry = 'SELECT Id,Cert_Date__c,Cert_Status__c,Admin_Id__c,PLMA_Status__c,'+
            'End_Date__c,Group_ID__c,Membership_Type__c,Start_Date__c,Status__c'+
            ' FROM Historical_PLMA__c WHERE Id = \''+historical.Id+'\'';
        Database.executeBatch(new B2BCreatePracticeHistoricalMembership(qry));
        Test.stopTest();
        Historical_PLMA__c historical1 = [SELECT Id,Data_Status__c FROM Historical_PLMA__c LIMIT 1];
    }
    
}