force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
                <default>true</default>
                <label>Credit Card Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <label>Stripe Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/B2BChargeCustomerInvoiceScheduler.cls
global class B2BChargeCustomerInvoiceScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {
        List<Invoice__c> invoices = [SELECT Id, Due_Date__c, Status__c, Stripe_Invoice_Id__c
                                     FROM Invoice__c 
                                     WHERE Due_Date__c = TODAY AND Status__c = 'Active'
                                    ];

        List<String> stripeInvoiceIds = new List<String>();
        for(Invoice__c invoice : invoices) {
            stripeInvoiceIds.add(invoice.Stripe_Invoice_Id__c);
        }

        List<Order> orders = [SELECT Id, InvoiceId__c, Account.Payment_Terms__c FROM Order WHERE InvoiceId__c IN :stripeInvoiceIds];
        
        List<String> eligibleInvoiceIds = new List<String>();
        for(Order order : orders) {
            if(order.Account.Payment_Terms__c == 'Credit Card Only') {
                eligibleInvoiceIds.add(order.InvoiceId__c);
            }
        }

        if(!eligibleInvoiceIds.isEmpty()) {
            B2BChargeCustomerInvoice.chargeCustomerInvoice(eligibleInvoiceIds);
        }
    }
}