force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
                <default>true</default>
                <label>Credit Card Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Invoice_Id__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Invoice_Id__c</fullName>
    <label>Stripe Invoice Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_URL__c</fullName>
    <label>Stripe Payment URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Order/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>Invoice Id</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsRenewal__c.field-meta.xml
<CustomField>
    <fullName>IsRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRenewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/B2BChargeCustomerInvoice.cls
public class B2BChargeCustomerInvoice {

    // @AuraEnabled
    // public static Invoice__c getInvoice(String invoiceId) {
    //     Invoice__c invoice= [SELECT Id, Stripe_Invoice_Id__c, Status__c,Stripe_Payment_URL__c FROM Invoice__c WHERE Id =:invoiceId];

    //     List<Order> order = [SELECT Id, Account.Payment_Terms__c, IsRenewal__c FROM Order WHERE InvoiceId__c = :invoice.Stripe_Invoice_Id__c];
        
    //     if(order.size() > 0) {
    //         if(order[0].IsRenewal__c) {
    //             if(order[0].Account.Payment_Terms__c == 'Credit Card Only') {
    //                 return invoice;
    //             }
    //         }
    //     }
    //     return null;
    // }
    
    // @AuraEnabled
    // public static String chargeCustomerInvoice(List<String> invoiceIds) {
    //     try {
    //         if(!invoiceIds.isEmpty()) {
    //             for (String invoiceId : invoiceIds) {
    //                 B2BStripePaymentController.chargeCustomerInvoice(invoiceId);
    //             }
    //         }
    //         return 'success';
    //     }
    //     catch(Exception e) {
    //         B2BHandleCustomException.LogException(e, 'B2BChargeCustomerInvoiceInvocable', 'chargeCustomerInvoice');
    //         return e.getMessage();
    //     } 
    // } 
}