force-app/main/default/objects/Account/fields/Payment_Terms__c.field-meta.xml
<CustomField>
    <fullName>Payment_Terms__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Net 30</fullName>
            </value>
            <value>
                <fullName>Net 60</fullName>
            </value>
            <value>
                <fullName>Credit Card Only</fullName>
                <default>true</default>
                <label>Credit Card Only</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/StripeCustomerId__c.field-meta.xml
<CustomField>
    <fullName>StripeCustomerId__c</fullName>
    <label>StripeCustomerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/IsRenewal__c.field-meta.xml
<CustomField>
    <fullName>IsRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRenewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/B2BRenewalInvoiceScheduler.cls
global class B2BRenewalInvoiceScheduler implements Schedulable {
    global void execute(SchedulableContext sc) {
    
        Map<String,String> minMaxDates = B2BUtils.calculateMinMaxRenewalOffsetRange();

        if(minMaxDates != null) {
            String minDate = minMaxDates.get('minDate');
            String maxDate = minMaxDates.get('maxDate');
        
            String query = 
                'SELECT Id, AccountId, Account.StripeCustomerId__c, Account.Payment_Terms__c'
                + ' FROM Order'
                + ' WHERE EffectiveDate >= ' + minDate + ' AND EffectiveDate <= ' + maxDate +
                + ' AND IsRenewal__c = TRUE'
                + ' AND Status = \'Draft\'' ;
            
            Integer batchSize = Integer.valueOf(System.Label.B2B_Invoice_Renewals_Batch_Size);
            
            B2BRenewalInvoiceBatch b = new B2BRenewalInvoiceBatch(query); 
            Database.executeBatch(b, batchSize);
        }
    }
}