force-app/main/default/objects/Account/fields/PracticeLevelRenewalDate__c.field-meta.xml
<CustomField>
    <fullName>PracticeLevelRenewalDate__c</fullName>
    <label>PracticeLevelRenewalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Business_Account__c.field-meta.xml
<CustomField>
    <fullName>Business_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Business Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments (Business Account)</relationshipLabel>
    <relationshipName>Account_Team_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BCalculatePLMARenewalDatesBatch.cls
public class B2BCalculatePLMARenewalDatesBatch implements Database.Batchable<sObject>, Database.Stateful {

    private String query;

    public B2BCalculatePLMARenewalDatesBatch(String query) {
        this.query = query;
    }

    public Database.QueryLocator start(Database.BatchableContext bc) {

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Practice_Level_Membership_Assignment__c> scope) {
        try {

            Set<String> accountIds = new Set<String>();

            for(Practice_Level_Membership_Assignment__c pm : scope) {
                accountIds.add(pm.Business_Account__c);
            }

            List<Account> accounts = [SELECT PracticeLevelRenewalDate__c FROM Account WHERE Id IN :accountIds];

            if(!accounts.isEmpty()) {
                List<Account> accountsToUpdate = new List<Account>();

                for (Account record : accounts) {
                    record.PracticeLevelRenewalDate__c = Date.today();
                    accountsToUpdate.add(record);
                }

                if(!accountsToUpdate.isEmpty()) {
                    update accountsToUpdate;
                }
            }
        } 
        catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BCalculatePLMARenewalDatesBatch', 'execute');
        }
    }

    public void finish(Database.BatchableContext bc) {}
}