force-app/main/default/objects/Account/fields/SX_Above_Unit_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SX_Above_Unit_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX Above Unit Lookup</label>
    <referenceTo>SX_Above_Unit__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SX_Unit_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SX_Unit_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX Unit Lookup</label>
    <referenceTo>SX_Unit__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Above_Unit__c/SX_Above_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Above Units along with corresponding Schoox IDs</description>
    <label>SX Above Unit</label>
    <nameField>
        <label>SX Above Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Above Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Above_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Role__c/SX_Role__c.object-meta.xml
<CustomObject>
    <description>Serves as a Salesforce Junction object between Units and Above Units</description>
    <label>SX Role</label>
    <nameField>
        <label>SX Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Role__c/fields/Above_Unit__c.field-meta.xml
<CustomField>
    <fullName>Above_Unit__c</fullName>
    <label>Above Unit</label>
    <referenceTo>SX_Above_Unit__c</referenceTo>
    <relationshipLabel>SX Roles</relationshipLabel>
    <relationshipName>SX_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Role__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>Unit</label>
    <referenceTo>SX_Unit__c</referenceTo>
    <relationshipLabel>SX Roles</relationshipLabel>
    <relationshipName>SX_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Role__c/fields/Unit_Above_Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit_Above_Unit__c</fullName>
    <externalId>true</externalId>
    <label>Unit Above Unit</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Unit__c/SX_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Units along with corresponding Schoox IDs</description>
    <label>SX Unit</label>
    <nameField>
        <label>SX Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateLMSUnit_CTRL.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-11-05 08:25:24
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:40:28
 * @ Description: Test class is CreateLMSUnit_CTRL_Test
 */

public with sharing class CreateLMSUnit_CTRL {
    @AuraEnabled( cacheable=false )
    public static String createUnit(Id accountId) {
        Account acc = [SELECT Name, SX_Above_Unit_Lookup__r.SX_ID__c FROM Account WHERE Id = :accountId LIMIT 1];
        SX_Unit__c lmsUnit = SchooxAPI.createLMSUnit(acc);
        insert lmsUnit;

        update new Account(Id = accountId, SX_Unit_Lookup__c = lmsUnit.Id);
        if (acc.SX_Above_Unit_Lookup__c != null) {
            SX_Role__c unitRole = new SX_Role__c(
                Unit__r = new SX_Unit__c(SX_ID__c = lmsUnit.SX_ID__c),
                Above_Unit__r = new SX_Above_Unit__c(SX_ID__c = acc.SX_Above_Unit_Lookup__r.SX_ID__c),
                Unit_Above_Unit__c = lmsUnit.SX_ID__c + '#' + acc.SX_Above_Unit_Lookup__r.SX_ID__c
            );
            insert unitRole;
        }
        return lmsUnit.SX_ID__c;
    }
}