force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <label>Invoice Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Amount_Charged__c.field-meta.xml
<CustomField>
    <fullName>Amount_Charged__c</fullName>
    <label>Amount Charged</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Disabled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_Payment_URL__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Payment_URL__c</fullName>
    <label>Stripe Payment URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Stripe_PDF_URL__c.field-meta.xml
<CustomField>
    <fullName>Stripe_PDF_URL__c</fullName>
    <label>Stripe PDF URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/InvoiceId__c.field-meta.xml
<CustomField>
    <fullName>InvoiceId__c</fullName>
    <label>InvoiceId</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Invoice Lines</relationshipLabel>
    <relationshipName>Invoice_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Line_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Line_Quantity__c</fullName>
    <label>Line Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice_Line__c/fields/Line_SubTotal__c.field-meta.xml
<CustomField>
    <fullName>Line_SubTotal__c</fullName>
    <label>Line SubTotal</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/B2BInvoiceHelperTest.cls
@isTest
public class B2BInvoiceHelperTest {
    
    @TestSetup static void makeData(){
        B2BTestDataFactory.createWebStore();
        String webStoreId  = [SELECT Id FROM WebStore WHERE Name = 'TestWebStore' LIMIT 1].Id;
        String accountId = B2BTestDataFactory.createAccount();
        String contactId = B2BTestDataFactory.createContact(accountId);
        User user = B2BTestDataFactory.createCommunityUser(contactId);

        Invoice__c invoice = new Invoice__c(
            Name = 'IN-TEST-01',  
            Amount_Charged__c = 10, 
            Period_Start_Date__c = Date.valueOf(System.today()), 
            Period_End_Date__c  = System.today().addDays(60), 
            Created_Date__c = System.today(), 
            Payment_Date__c = System.today().addDays(59), 
            Stripe_PDF_URL__c = 'https://www.google.com/', 
            Stripe_Payment_URL__c = 'https://www.google.com/',
            Account_Id__c = accountId,
            Status__c = 'Active'
        );
        insert invoice;

        Invoice_Line__c invoiceLine = new Invoice_Line__c(
            Name = 'IN-LINE-TEST-01',
            InvoiceId__c = invoice.Id,
            Line_Quantity__c = 1,
            Line_SubTotal__c = 10,
            Line_Total__c = 10
        );
        insert invoiceLine;
    }

    @isTest static void testGetInvoices() {

        User user = [SELECT Id FROM User WHERE Username = 'testuser@gmail.com' LIMIT 1];

        Test.StartTest();
        List<B2BInvoiceHelper.InvoiceWrapper> result;
        System.runAs(user) {
            result = B2BInvoiceHelper.getInvoices();
        }
        Test.StopTest();
    }
}