force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BBuyerGroupAssignemntController.cls
/**
 * @description       : 
 * @author            : Poojitha Anthati
 * @group             : 
 * @last modified on  : 09-18-2025
 * @last modified by  : Poojitha Anthati
**/
public class B2BBuyerGroupAssignemntController {

    public static void handleBuyerGroupsForILMA(Account_Membership__c iLMA) {
        if(iLMA.Account_Id__c != null) {
            List<String> buyerGroupIdList = B2BBuyerGroupAssignmentService.getEligibleILMABuyerGroups(iLMA);
        
            B2BBuyerGroupAssignmentService.createBuyerGroupMembers(buyerGroupIdList, iLMA.Account_Id__c);
        }
    }

    public static void handleBuyerGroupsForAccount(Account account) {
        List<Account_Membership__c> activeMemberships = B2BBuyerGroupAssignmentService.getActiveMemberships(account.Id);

        if(activeMemberships != null) {

            Set<String> buyerGroupIdsToAssignSet = new Set<String>();
            Set<String> buyerGroupIdsToUnassignSet = new Set<String>();

            for(Account_Membership__c am : activeMemberships) {
                buyerGroupIdsToAssignSet.addAll(B2BBuyerGroupAssignmentService.getEligibleILMABuyerGroups(am));
                buyerGroupIdsToUnassignSet.addAll(B2BBuyerGroupAssignmentService.getInEligibleILMABuyerGroups(am));
            }

            List<String> buyerGroupIdsToAssign = new List<String>(buyerGroupIdsToAssignSet);
            List<String> buyerGroupIdsToUnassign = new List<String>(buyerGroupIdsToUnassignSet);

            B2BBuyerGroupAssignmentService.deleteBuyerGroupMembers(buyerGroupIdsToUnassign, account.Id);
            B2BBuyerGroupAssignmentService.createBuyerGroupMembers(buyerGroupIdsToAssign, account.Id);
        }
    }

    public static void handleBuyerGroupsSync(Account account) {
        List<String> existingBuyerGroupIds = B2BBuyerGroupAssignmentService.getAllBuyerGroupAssignments(account.Id);
        System.debug('## Existing Buyer Groups:' + existingBuyerGroupIds);

        List<Account_Membership__c> activeILMAs = B2BBuyerGroupAssignmentService.getActiveMemberships(account.Id);

        if(activeILMAs != null) {
            Set<String> eligibleBuyerGroupIdsSet = new Set<String>();

            for(Account_Membership__c am : activeILMAs) {
                eligibleBuyerGroupIdsSet.addAll(B2BBuyerGroupAssignmentService.getEligibleBuyerGroups(am));
            }
            List<String> buyerGroupIdsToAssign = new List<String>(eligibleBuyerGroupIdsSet);
            System.debug('## Buyer group ids to Assign:' + buyerGroupIdsToAssign);

            List<String> buyerGroupIdsToUnassign = new List<String>();
            for (String id : existingBuyerGroupIds) {
                if (!buyerGroupIdsToAssign.contains(id)) {
                    buyerGroupIdsToUnassign.add(id);
                }
            }
            System.debug('## Buyer group ids to Unassign:' + buyerGroupIdsToUnassign);
            if(buyerGroupIdsToUnassign != null) {
                B2BBuyerGroupAssignmentService.deleteBuyerGroupMembers(buyerGroupIdsToUnassign, account.Id); 
            }

            List<String> missedBuyerGroupIdsToAssign = new List<String>();
            for(String id : buyerGroupIdsToAssign) {
                if(!existingBuyerGroupIds.contains(id)) {
                    missedBuyerGroupIdsToAssign.add(id);
                }
            }
            System.debug('## Missed Buyer group ids to Assign:' + missedBuyerGroupIdsToAssign);
            if(missedBuyerGroupIdsToAssign != null){
                B2BBuyerGroupAssignmentService.createBuyerGroupMembers(missedBuyerGroupIdsToAssign, account.Id);
            }
        } 
        else if(existingBuyerGroupIds != null) {
            B2BBuyerGroupAssignmentService.deleteBuyerGroupMembers(existingBuyerGroupIds, account.Id);
        }
    }
}