force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Certification_Kit_Order__c.field-meta.xml
<CustomField>
    <fullName>Certification_Kit_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Certification Kit Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Order_Summary__c.field-meta.xml
<CustomField>
    <fullName>Order_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Certification Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Individual_Certification_Kit__c.field-meta.xml
<CustomField>
    <fullName>Individual_Certification_Kit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Individual Certification Kit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Memberships (Individual Welcome Kit)</relationshipLabel>
    <relationshipName>Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual Level Membership</fullName>
            </value>
            <value>
                <fullName>Practice Level Membership</fullName>
            </value>
            <value>
                <fullName>Certification Kit</fullName>
            </value>
            <value>
                <fullName>Individual Academia Membership</fullName>
            </value>
            <value>
                <fullName>Permanent Membership</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BHandleCertificationKitBeforeOrder.cls
public without sharing class B2BHandleCertificationKitBeforeOrder {

    public static Boolean isRunTrigger = true;

    public static void updateOrderItems(String orderId) {
        try {
            isRunTrigger = false;
            
            List<OrderItem> orderItems = [SELECT Id, Product2Id, Product2.Name, Product2.Product_Group__c, Product2.ProductClass
                                        FROM OrderItem 
                                        WHERE OrderId = :orderId
                                        ];

            List<Id> productIds = new List<Id>();

            for(OrderItem oi: orderItems) {
                if(oi.Product2.Product_Group__c == 'Certification Kit') {
                    productIds.add(oi.Product2Id);
                }
                else {
                    continue;
                }
            }
            updateCertificationKitStatus(productIds, orderId);
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BHandleCertificationKitBeforeOrder', 'updateOrderItems');
        }
    }

    public static Boolean runTrigger() {
        return isRunTrigger == true ? true : false;
    }

    public static void updateCertificationKitStatus(List<Id> productIds, String orderId) {
        try {
            String accountId = B2BUtils.getUserAccountID();

            List<Account_Membership__c> accountMemberships = [SELECT Id, Name, Welcome_Kit_Status__c, Certification_Kit_Order__c, Order_Summary__c
                                                            FROM Account_Membership__c
                                                            WHERE Account_Id__c =:accountId AND Membership__r.Individual_Certification_Kit__r.Id IN :productIds 
                                                            AND Welcome_Kit_Status__c = 'Unclaimed'
                                                            ];
                                            
            List<Account_Membership__c> itemsToUpdate = new List<Account_Membership__c>();                                                 
            for(Account_Membership__c am : accountMemberships) {
                am.Welcome_Kit_Status__c = 'Claimed';
                am.Certification_Kit_Order__c = orderId;

                itemsToUpdate.add(am);
            }
            
            if(!itemsToUpdate.isEmpty()) {
                update itemsToUpdate;
            }
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BHandleCertificationKitBeforeOrder', 'updateCertificationKitStatus');
        }
    }
}