force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>IF( Membership_Level__c = &apos;Practice&apos;, Practice_Level_Membership_Assignment__r.Expiration_Date__c,
				IF(
    NOT(ISBLANK(Account_Assignment_Date__c)),
    ADDMONTHS(Account_Assignment_Date__c, 12),
    ADDMONTHS(DATEVALUE(CreatedDate) , 12)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/IsRenewal__c.field-meta.xml
<CustomField>
    <fullName>IsRenewal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsRenewal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>ADDMONTHS( Start_Date__c ,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>formula- ADDMONTHS( Start_Date__c ,12)</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BIndividualLevelRenewalsHelper.cls
public class B2BIndividualLevelRenewalsHelper {

    public static List<Account_Membership__c> getEligibleMembershipAssignments(String parentAccountId) {
        try {
            Map<String,String> minMaxDates = B2BUtils.calculateMinMaxRenewalOffsetRange();
            String minDate = minMaxDates.get('minDate');
            String maxDate = minMaxDates.get('maxDate');

            String queryString = 'SELECT Id, Account_Id__c, Membership__c, Practice_Level_Membership_Assignment__c, Parent_Id__c ' +
                                 'FROM Account_Membership__c ' +
                                 'WHERE Expiration_Date__c >= ' + minDate + ' AND Expiration_Date__c <= ' + maxDate +
                                 ' AND Status__c != \'Canceled\' AND Status__c != \'Voided\'' +
                                 ' AND Parent_Id__c = :parentAccountId';

            List<Account_Membership__c> memberships = Database.query(queryString);

            return memberships.isEmpty() ? null : memberships;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getEligibleMembershipAssignments');
            return null;
        }
    }

    public static String getWebStoreIdByName(String storeName) {
        try {
            return [
                SELECT Id 
                FROM WebStore 
                WHERE Name = :storeName 
                LIMIT 1
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getWebStoreIdByName');
            return null;
        }
    }

    public static Date getEffectiveOrderDate(String paymentTerms) {
        try {
            return B2BUtils.getTargetRenewalDate();
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getEffectiveOrderDate');
            return null;
        }
    }

    public static String getOrderDeliveryMethodId() {
        try {
            return [
                SELECT Id, Name 
                FROM OrderDeliveryMethod
                LIMIT 1
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getOrderDeliveryMethodId');
            return null;
        }
    }

    public static String getRenewalProductId(String membershipId) {
        try {
            return [
                SELECT Id, Membership__c 
                FROM Product2 
                WHERE Membership__c = :membershipId
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getRenewalProductId');
            return null;
        }
    }

    public static Decimal getRenewalProductPrice(String accountId, String productId) {

        try {
            return B2BUtils.getProductPriceByAccountId(accountId, productId);
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getRenewalProductPrice');
            return null;
        }
    }

    public static String getExistingOrderId(Account account) {
        try {
            List<Order> orders = [
                SELECT Id 
                FROM Order 
                WHERE AccountId = :account.Id 
                AND IsRenewal__c = true 
                AND CreatedDate = TODAY
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];
            return orders.size() > 0 ? orders[0].Id : null;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getExistingOrderId');
            return null;
        }
    }

    public static String getOrderDeliveryGroupId(String orderId) {
        try {
            return [
                SELECT Id
                FROM OrderDeliveryGroup
                WHERE OrderId = :orderId
                LIMIT 1
            ].Id;
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BIndividualLevelRenewalsHelper', 'getOrderDeliveryGroupId');
            return null;
        }
    }
}