force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Assignment_Date__c</fullName>
    <label>Account Assignment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <formula>Membership__r.Job_Id__c</formula>
    <label>Job Id</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Purchaser_Account__c.field-meta.xml
<CustomField>
    <fullName>Purchaser_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Purchaser Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Memberships1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Course Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Certification Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/B2BSchooxAPIControllerTest.cls
@IsTest
public class B2BSchooxAPIControllerTest {

    @TestSetup static void makeData(){
        B2BTestDataFactory.createWebStore();
        String accountId = B2BTestDataFactory.createAccount();

        Account account = [SELECT Id, SX_User_Id__pc FROM Account WHERE Name = 'Test Account' LIMIT 1];
        account.SX_User_Id__pc = '1918259581';
        update account;

        Membership__c m = new Membership__c(
            Name = 'Test Membership',
            Job_Id__c = 123456
        );
        insert m;

        Account_Membership__c am = new Account_Membership__c(
            Membership__c = m.Id,
            Account_Id__c = accountId,
            Parent_Id__c = accountId,
            Purchaser_Account__c = accountId,
            Account_Assignment_Date__c = System.today(),
            Start_Date__c = System.today(),
            Welcome_Kit_Status__c = 'Unavailable',
            Status__c = 'Active'
        );
        insert am;
    }

    @isTest static void testHandleJobAssignmentManual() {
        Test.StartTest();
        String accountId = [SELECT Id, SX_User_Id__pc FROM Account WHERE Name = 'Test Account' LIMIT 1].Id;

        Account_Membership__c am = [SELECT Id, Account_Id__c, Job_Id__c FROM Account_Membership__c WHERE Account_Id__c = :accountId];
        try{
            Test.setMock(HttpCalloutMock.class, new B2BSchooxApiCallMock());
            B2BSchooxAPIController.handleJobAssignmentManual(am.Id);
        }
        catch(Exception e) {}
        Test.StopTest();
    }

    @isTest static void testHandleJobUnassignmentManual() {
        Test.StartTest();
        String accountId = [SELECT Id, SX_User_Id__pc FROM Account WHERE Name = 'Test Account' LIMIT 1].Id;

        Account_Membership__c am = [SELECT Id, Account_Id__c, Job_Id__c FROM Account_Membership__c WHERE Account_Id__c = :accountId];
        try{
            Test.setMock(HttpCalloutMock.class, new B2BSchooxApiCallMock());
            B2BSchooxAPIController.handleJobUnassignmentManual(am.Id);
        }
        catch(Exception e) {}
        Test.StopTest();
    }

    @isTest static void testGetAllJobs() {
        Test.StartTest();
        try{
            Test.setMock(HttpCalloutMock.class, new B2BSchooxApiCallMock());
            B2BSchooxAPIController.getAllJobs();
        }
        catch(Exception e) {}
        Test.StopTest();
    }
}