force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>IF( Membership_Level__c = &apos;Practice&apos;, Practice_Level_Membership_Assignment__r.Expiration_Date__c,
				IF(
    NOT(ISBLANK(Account_Assignment_Date__c)),
    ADDMONTHS(Account_Assignment_Date__c, 12),
    ADDMONTHS(DATEVALUE(CreatedDate) , 12)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Parent_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Parent Id)</relationshipLabel>
    <relationshipName>Parent_Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2BCalculateILMARenewalDatesScheduler.cls
global class B2BCalculateILMARenewalDatesScheduler implements Schedulable {

    global void execute(SchedulableContext sc) {

        Map<String,String> minMaxDates = B2BUtils.calculateMinMaxRenewalOffsetRange();

        if(minMaxDates != null) {
            String minDate = minMaxDates.get('minDate');
            String maxDate = minMaxDates.get('maxDate');

            String query = 'SELECT Parent_Id__c '+
                           'FROM Account_Membership__c ' +
                           'WHERE Expiration_Date__c >= ' + minDate + ' AND Expiration_Date__c <= ' + maxDate;

            Integer batchSize = Integer.valueOf(System.Label.B2B_Calculate_Renewal_Dates_Batch_Size);

            B2BCalculateILMARenewalDatesBatch b = new B2BCalculateILMARenewalDatesBatch(query); 
            Database.executeBatch(b, batchSize);
        }
    }
}