force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/Buyer_Group_Membership__c.object-meta.xml
<CustomObject>
    <label>Buyer Group Membership</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Buyer Group Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buyer Group Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Buyer_Group__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Buyer Group</label>
    <referenceTo>BuyerGroup</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Buyer_Group_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Buyer Group Memberships</relationshipLabel>
    <relationshipName>Buyer_Group_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/B2BMembershipEndHelper.cls
public class B2BMembershipEndHelper {

    public static List<Id> getBuyerGroupMemberships(String membershipId) {
        try {
            List<Buyer_Group_Membership__c> bgmList = [
                SELECT Id, Buyer_Group__c 
                FROM Buyer_Group_Membership__c 
                WHERE Membership__c = :membershipId
            ];

            List<Id> buyerGroupIds = new List<Id>();
            if(bgmList.size() > 0) {
                for(Buyer_Group_Membership__c bgm : bgmList) {
                    buyerGroupIds.add(bgm.Buyer_Group__c);
                }
                return buyerGroupIds;
            }
            return null;
        } 
        catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BMembershipEndHelper', 'getBuyerGroupMembership');
            return null;
        }
    }
    
    public static List<Account_Membership__c> getActiveILMAofSameType(String accountId, String membershipId) {
        try {
            List<Account_Membership__c> activeILMAs = [SELECT Id 
                                                       FROM Account_Membership__c 
                                                       WHERE Account_Id__c = :accountId  
                                                       AND Membership__c = :membershipId
                                                       AND Status__c = 'Active'
                                                      ];

            if(activeILMAs.size() > 0) {
                return activeILMAs;
            }
            return null;
        }
        catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BMembershipEndHelper', 'getActiveILMAofSameType');
            return null;
        }
    }

    public static void unassignBuyerGroups(String accountId, List<Id> buyerGroupIds) {
        try {
            List<BuyerGroupMember> buyerGroupsAssignments = [
                SELECT Id 
                FROM BuyerGroupMember 
                WHERE BuyerId = :accountId 
                AND BuyerGroupId IN :buyerGroupIds
            ];

            if(buyerGroupsAssignments.size() > 0) {
                delete buyerGroupsAssignments;
            }
        } 
        catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BMembershipEndHelper', 'unassignBuyerGroups');
        }
    }
}