force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Assigned Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Memberships (Account Id)</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Historical_Membership__c.field-meta.xml
<CustomField>
    <fullName>Historical_Membership__c</fullName>
    <label>Historical Membership</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <formula>Membership__r.Job_Id__c</formula>
    <label>Job Id</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Last_Schoox_Job_Assignment_Exception__c.field-meta.xml
<CustomField>
    <fullName>Last_Schoox_Job_Assignment_Exception__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Last Schoox Job Assignment Exception</label>
    <referenceTo>B2B_Custom_Exception__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments (Last Schoox Job Assignment Exception)</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
                <label>Revoked</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/Historical_Membership__c.object-meta.xml
<CustomObject>
    <label>Historical Membership</label>
    <nameField>
        <displayFormat>HM-{00000}</displayFormat>
        <label>Historical Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Job_Id__c.field-meta.xml
<CustomField>
    <fullName>Job_Id__c</fullName>
    <label>Job Id</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/B2BSchooxJobsAssignmentBatch.cls
public class B2BSchooxJobsAssignmentBatch implements Database.Batchable<sObject>, Database.Stateful {

    public B2BSchooxJobsAssignmentBatch() { }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Account_Id__c, Job_Id__c FROM Account_Membership__c WHERE Historical_Membership__c != null and Status__c = \'Active\' AND Membership__r.Active__c = true';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Account_Membership__c> accountMemberships){

        try {
            Map<String, List<Integer>> accountJobMap = new Map<String, List<Integer>>();
            Map<String, List<Account_Membership__c>> accountILMAMap = new Map<String, List<Account_Membership__c>>();

            for(Account_Membership__c ilma : accountMemberships) {
                if (ilma.Account_Id__c != null && ilma.Job_Id__c != null) {
                    if (!accountJobMap.containsKey(ilma.Account_Id__c)) {
                        accountJobMap.put(ilma.Account_Id__c, new List<Integer>());
                    }
                    accountJobMap.get(ilma.Account_Id__c).add(Integer.valueOf(ilma.Job_Id__c));
                }
            }

            List<Account_Membership__c> failedSchooxJobpAssignments = new List<Account_Membership__c>();
            for (String accountId : accountJobMap.keySet()) {
                try {
                    B2BSchooxAPIController.handleJobAssignmnet(accountId, accountJobMap.get(accountId));
                }
                catch(Exception e) {
                    for(Account_Membership__c ilma : accountILMAMap.get(accountId)){
                        String errorMessage = 'Schoox Jobs Assignment Failed for the Account: ' + accountId + 
                                          ' | Failed Job Id: ' + ilma.Job_Id__c;
                        
                        ilma.Last_Schoox_Job_Assignment_Exception__c = B2BHandleCustomException.LogException(new HistoricalOrdersException(errorMessage), 'Historical Memberships', 'Schoox Jobs Assignment');
                        failedSchooxJobpAssignments.add(ilma);
                    }
                }
            }
            Database.update(failedSchooxJobpAssignments);
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'Historical Memberships', 'Schoox Jobs Assignment - Batch Level Failure');
        }
    }

    public void finish(Database.BatchableContext bc){

    }

    public class HistoricalOrdersException extends Exception {}
}