force-app/main/default/objects/Account_Membership__c/Account_Membership__c.object-meta.xml
<CustomObject>
    <label>Individual Membership Assignment</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Individual Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Membership__c/fields/Account_Assignment_Date__c.field-meta.xml
<CustomField>
    <fullName>Account_Assignment_Date__c</fullName>
    <label>Account Assignment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Historical_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Historical_End_Date__c</fullName>
    <label>Historical End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Historical_Membership__c.field-meta.xml
<CustomField>
    <fullName>Historical_Membership__c</fullName>
    <label>Historical Membership</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Historical_User_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_User_Id__c</fullName>
    <label>Historical User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Individual Level Memberships</relationshipLabel>
    <relationshipName>Account_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <formula>TEXT(Membership__r.Membership_Level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Membership Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Practice_Level_Membership_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Practice_Level_Membership_Assignment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Practice Level Membership Assignment</label>
    <referenceTo>Practice_Level_Membership_Assignment__c</referenceTo>
    <relationshipLabel>Individual Membership Assignments</relationshipLabel>
    <relationshipName>Individual_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Course Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account_Membership__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Certification Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/Historical_Membership__c.object-meta.xml
<CustomObject>
    <label>Historical Membership</label>
    <nameField>
        <displayFormat>HM-{00000}</displayFormat>
        <label>Historical Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Historical Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historical_Membership__c/fields/Course_Id__c.field-meta.xml
<CustomField>
    <fullName>Course_Id__c</fullName>
    <label>Course Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/Historical_Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Historical_Order_Id__c</fullName>
    <label>Historical Order Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/Post_Id__c.field-meta.xml
<CustomField>
    <fullName>Post_Id__c</fullName>
    <label>Post Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/Successful_Insert__c.field-meta.xml
<CustomField>
    <fullName>Successful_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Successful Insert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <label>User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historical_Membership__c/fields/User_Membership_Date__c.field-meta.xml
<CustomField>
    <fullName>User_Membership_Date__c</fullName>
    <label>User Membership Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Membership__c/Membership__c.object-meta.xml
<CustomObject>
    <label>Membership</label>
    <nameField>
        <label>Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Membership__c/fields/Membership_Level__c.field-meta.xml
<CustomField>
    <fullName>Membership_Level__c</fullName>
    <label>Membership Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Practice</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Membership__c/fields/WC_Id__c.field-meta.xml
<CustomField>
    <fullName>WC_Id__c</fullName>
    <label>WC Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Historical_Membership__c.field-meta.xml
<CustomField>
    <fullName>Historical_Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Historical Membership</label>
    <referenceTo>Historical_Membership__c</referenceTo>
    <relationshipLabel>Practice Level Membership Assignments</relationshipLabel>
    <relationshipName>Practice_Level_Membership_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipName>Account_Team_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Welcome_Kit_Status__c.field-meta.xml
<CustomField>
    <fullName>Welcome_Kit_Status__c</fullName>
    <label>Welcome Kit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unavailable</fullName>
            </value>
            <value>
                <fullName>Unclaimed</fullName>
            </value>
            <value>
                <fullName>Claimed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Membership__c.field-meta.xml
<CustomField>
    <fullName>Membership__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership</label>
    <referenceTo>Membership__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/WC_Id__c.field-meta.xml
<CustomField>
    <fullName>WC_Id__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/B2BCreateHistoricalMembershipsBatch.cls
public class B2BCreateHistoricalMembershipsBatch implements Database.Batchable<sObject>, Database.Stateful {

    public B2BCreateHistoricalMembershipsBatch() { }

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Cancelled_Date__c, Course_Id__c, End_Date__c, First_Name__c, Historical_Order_Id__c, Last_Name__c, Name, Post_Id__c, Product_Id__c, Start_Date__c, Successful_Insert__c, User_Email__c, User_Id__c,  User_Membership_Date__c FROM Historical_Membership__c WHERE Successful_Insert__c = false';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Historical_Membership__c> scope){

        try {
            Set<String> wcIds = new Set<String>();
            for(Historical_Membership__c hm : scope) {
                wcIds.add(hm.Product_Id__c);
            }

            List<Product2> products = [SELECT Id, Name, Membership__r.Membership_Level__c, Membership__c, WC_Id__c 
                                       FROM Product2 
                                       WHERE WC_Id__c IN :wcIds];
           
            List<Map<String, String>> membershipMapList = new List<Map<String, String>>();
            List<Map<String, String>> membershipLevelMapList = new List<Map<String, String>>();
            if(products.size() > 0) {
                for(Product2 p : products) {
                    Map<String, String> membershipMap = new Map<String, String>();
                    Map<String, String> membershipLevelMap = new Map<String, String>();
                    
                    if(p.WC_Id__c != null) {
                        membershipMap.put(p.WC_Id__c, p.Membership__c);
                        membershipMapList.add(membershipMap);

                        membershipLevelMap.put(p.WC_Id__c, p.Membership__r.Membership_Level__c);
                        membershipLevelMapList.add(membershipLevelMap);
                    }
                }
            }
            
            List<Account_Membership__c> accountMemberships = new List<Account_Membership__c>();
            List<Practice_Level_Membership_Assignment__c> practiceMemberships = new List<Practice_Level_Membership_Assignment__c>();
            for(Historical_Membership__c hm : scope) {

                String membershipId;

                if(membershipMapList.size() > 0) {
                    for(Map<String, String> existingMap : membershipMapList) {
                        if(existingMap.containsKey(hm.Product_Id__c)) {
                            membershipId = existingMap.get(hm.Product_Id__c);
                            break;
                        }
                    }
                }

                String membershipLevel;
                if(membershipLevelMapList.size() > 0) {
                    for(Map<String, String> existingMap : membershipLevelMapList) {
                        if(existingMap.containsKey(hm.Product_Id__c)) {
                            membershipLevel = existingMap.get(hm.Product_Id__c);
                            break;
                        }
                    }
                } 

                if(membershipId != null && membershipLevel != null) {
                    if(membershipLevel == 'Individual') {
                        Account_Membership__c am = new Account_Membership__c();
                        am.Account_Assignment_Date__c = hm.User_Membership_Date__c;
                        am.Start_Date__c = hm.Start_Date__c;
                        am.Historical_End_Date__c = hm.End_Date__c;
                        am.Welcome_Kit_Status__c = 'Unavailable';
                        am.Historical_Order_Id__c = hm.Historical_Order_Id__c;
                        am.Historical_User_Id__c = hm.User_Id__c;
                        am.Cancelled_Date__c = hm.Cancelled_Date__c;
                        am.Membership__c = membershipId;

                        accountMemberships.add(am);
                    }
                    else if(membershipLevel == 'Practice') {
                        Practice_Level_Membership_Assignment__c pm = new Practice_Level_Membership_Assignment__c();
                        pm.Start_Date__c = hm.Start_Date__c;
                        pm.Welcome_Kit_Status__c = 'Unavailable';
                        pm.Historical_Order_Id__c = hm.Historical_Order_Id__c;
                        pm.Historical_User_Id__c = hm.User_Id__c;
                        pm.Membership__c = membershipId;

                        practiceMemberships.add(pm);
                    }
                }
            }

            List<Historical_Membership__c> historicalMembershipsToBeUpdated = new List<Historical_Membership__c>();
            if(!accountMemberships.isEmpty()) {
                insert accountMemberships;
            }
            if(!practiceMemberships.isEmpty()) {
                insert practiceMemberships;
            }

            for(Historical_Membership__c hm : scope) {
                hm.Successful_Insert__c = true;
                historicalMembershipsToBeUpdated.add(hm);
            }
            update historicalMembershipsToBeUpdated;
        }
        catch(Exception e) {
            B2BHandleCustomException.LogException(e, 'Historical Memberships', 'Membership Creation');
        }        
    }

    public void finish(Database.BatchableContext bc){

    }
}