force-app/main/default/objects/Practice_Level_Membership_Assignment__c/Practice_Level_Membership_Assignment__c.object-meta.xml
<CustomObject>
    <label>Practice Level Membership Assignment</label>
    <nameField>
        <displayFormat>ATM-{0000}</displayFormat>
        <label>Account Team Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Level Membership Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <formula>ADDMONTHS( Start_Date__c ,12)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>formula- ADDMONTHS( Start_Date__c ,12)</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Practice_Level_Membership_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Early</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
                <label>Expired</label>
            </value>
            <value>
                <fullName>Voided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/B2BPLMAMembershipEndBatch.cls
public class B2BPLMAMembershipEndBatch implements Database.Batchable<sObject>, Database.Stateful {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query = 'SELECT Id, Status__c, Expired__c ' +
                       'FROM Practice_Level_Membership_Assignment__c ' + 
                       'WHERE Expiration_Date__c =  YESTERDAY';
        
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Practice_Level_Membership_Assignment__c> scope) {
        try {
            List<Practice_Level_Membership_Assignment__c> plmasToUpdate = new List<Practice_Level_Membership_Assignment__c>();

            for(Practice_Level_Membership_Assignment__c plma : scope) {
                plma.Status__c = 'Complete';
                plmasToUpdate.add(plma);
            }
            
            if(plmasToUpdate.size() > 0) {
                update plmasToUpdate;
            }
        } catch (Exception e) {
            B2BHandleCustomException.LogException(e, 'B2BPLMAMembershipEndBatch', 'execute');
        }
    }

    public void finish(Database.BatchableContext bc) {}
}