force-app/main/default/objects/SX_Above_Unit__c/SX_Above_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Above Units along with corresponding Schoox IDs</description>
    <label>SX Above Unit</label>
    <nameField>
        <label>SX Above Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Above Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Above_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Role__c/SX_Role__c.object-meta.xml
<CustomObject>
    <description>Serves as a Salesforce Junction object between Units and Above Units</description>
    <label>SX Role</label>
    <nameField>
        <label>SX Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Role__c/fields/Unit_Above_Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit_Above_Unit__c</fullName>
    <externalId>true</externalId>
    <label>Unit Above Unit</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Unit__c/SX_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Units along with corresponding Schoox IDs</description>
    <label>SX Unit</label>
    <nameField>
        <label>SX Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllUnitsEXT.cls
/**
 * @ Author: Gary Guthrie
 * @ Create Time: 2022-10-29 17:55:26
 * @ Modified by: Gary Guthrie
 * @ Modified time: 2022-11-18 00:01:02
 * @ Description: Test class is GetAllUnitsEXT_Test
 */

public with sharing class GetAllUnitsEXT {
    private ApexPages.StandardSetController stdSetController;

    public GetAllUnitsEXT(ApexPages.StandardSetController ctrl) {
        this.stdSetController = ctrl;
    }

    public pageReference getBack() {
        Map<String, List<SObject>> objectListByName = SchooxAPI.getAllUnits();
        List<SX_Above_Unit__c> aboveList = SchooxAPI.getAllAboveUnits();
        List<SX_Unit__c> unitList = objectListByName.get('Unit');
        upsert unitList SX_ID__c;
        System.debug('unitList: ' + unitList.size());
        // System.debug(JSON.serializePretty(unitList));

        List<SX_Above_Unit__c> aboveUnitList = objectListByName.get('Above Unit');
        Set<String> aboveUnitNames = new Set<String>();
        for (SX_Above_Unit__c rec : aboveUnitList) {
            aboveUnitNames.add(rec.Name);
        }
        for (SX_Above_Unit__c rec : aboveList) {
            if(!aboveUnitNames.contains(rec.Name)){
                aboveUnitList.add(rec);
            }
        }
        upsert aboveUnitList SX_ID__c;
        System.debug('aboveUnitList: ' + aboveUnitList.size());
        // System.debug(JSON.serializePretty(aboveUnitList));

        List<SX_Role__c> roleList = objectListByName.get('Role');
        upsert roleList Unit_Above_Unit__c;
        System.debug('roleList: ' + roleList.size());
        // System.debug(JSON.serializePretty(roleList));

        return this.stdSetController.cancel();
    }
}