force-app/main/default/objects/SX_Above_Unit__c/SX_Above_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Above Units along with corresponding Schoox IDs</description>
    <label>SX Above Unit</label>
    <nameField>
        <label>SX Above Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Above Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Above_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Deleted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_Active__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Course Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_Job__c/SX_Job__c.object-meta.xml
<CustomObject>
    <description>Tracks the Schoox LMS Jobs along with corresponding Schoox IDs</description>
    <label>SX Job</label>
    <nameField>
        <label>SX Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Job__c/fields/SX_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Job_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Job ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_Role__c/SX_Role__c.object-meta.xml
<CustomObject>
    <description>Serves as a Salesforce Junction object between Units and Above Units</description>
    <label>SX Role</label>
    <nameField>
        <label>SX Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Roles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Role__c/fields/Unit_Above_Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit_Above_Unit__c</fullName>
    <externalId>true</externalId>
    <label>Unit Above Unit</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Unit__c/SX_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Units along with corresponding Schoox IDs</description>
    <label>SX Unit</label>
    <nameField>
        <label>SX Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllSchooxScheduler.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-10-11 15:36:07
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:42:06
 * @ Description: GetAllSchooxScheduler_Test
 * new GetAllSchooxScheduler().execute(null);
 * System.schedule('Schoox Jobs, Units, Courses Sync', '0 0 06,18 ? * MON-FRI', new GetAllSchooxScheduler());
 */

public without sharing class GetAllSchooxScheduler implements Schedulable {
    public void execute(SchedulableContext sc) {
        getJobs();
        getUnits();
        getCourse();
    }

    @Future(Callout=true)
    private static void getJobs() {
        List<SX_Job__c> sxJobList = SchooxAPI.getAllJob();

        upsert sxJobList SX_Job_ID__c;
        System.debug('sxJobList: ' + sxJobList.size());
    }

    @Future(Callout=true)
    private static void getUnits(){
        Map<String, List<SObject>> objectListByName = SchooxAPI.getAllUnits();
        List<SX_Above_Unit__c> aboveList = SchooxAPI.getAllAboveUnits();
        List<SX_Unit__c> unitList = objectListByName.get('Unit');
        upsert unitList SX_ID__c;
        System.debug('unitList: ' + unitList.size());

        List<SX_Above_Unit__c> aboveUnitList = objectListByName.get('Above Unit');
        Set<String> aboveUnitNames = new Set<String>();
        for (SX_Above_Unit__c rec : aboveUnitList) {
            aboveUnitNames.add(rec.Name);
        }
        for (SX_Above_Unit__c rec : aboveList) {
            if(!aboveUnitNames.contains(rec.Name)){
                aboveUnitList.add(rec);
            }
        }
        upsert aboveUnitList SX_ID__c;
        System.debug('aboveUnitList: ' + aboveUnitList.size());

        List<SX_Role__c> roleList = objectListByName.get('Role');
        upsert roleList Unit_Above_Unit__c;
        System.debug('roleList: ' + roleList.size());
    }

    @Future(Callout=true)
    private static void getCourse(){
        List<SX_Courses__c> coursesToUpdate = new List<SX_Courses__c>();

        List<SX_Courses__c> activeCourses = SchooxAPI.getAllCourse('active');
        for (SX_Courses__c course : activeCourses) {
            course.SX_Course_Active__c = true;
            course.Status__c = 'Active';
        }
        coursesToUpdate.addAll(activeCourses);

        List<SX_Courses__c> deletedCourses = SchooxAPI.getAllCourse('deleted');
        for (SX_Courses__c course : deletedCourses) {
            course.SX_Course_Active__c = false;
            course.Status__c = 'Deleted';
        }
        coursesToUpdate.addAll(deletedCourses);

        List<SX_Courses__c> archivedCourses = SchooxAPI.getAllCourse('archived');
        for (SX_Courses__c course : archivedCourses) {
            course.SX_Course_Active__c = false;
            course.Status__c = 'Archived';
        }
        coursesToUpdate.addAll(archivedCourses);

        if (!Test.isRunningTest()) {
            upsert coursesToUpdate SX_Course_ID__c;
        }        
        System.debug('coursesToUpdate: ' + coursesToUpdate.size());
    }
}