force-app/main/default/objects/Contact/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>SX_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX Enrollment</label>
    <referenceTo>SX_Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX LMS User</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_User_Id__c.field-meta.xml
<CustomField>
    <fullName>SX_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>SX User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_Active__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Course Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_Description__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_Description__c</fullName>
    <label>Course Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_Image_URL__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_Image_URL__c</fullName>
    <label>SX Course Image URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_URL__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_URL__c</fullName>
    <label>SX Course URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/SX_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Tracks the Schoox LMS course enrollment for each learner along with key statistics.</description>
    <label>SX Enrollment</label>
    <nameField>
        <label>SX Enrollment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Enrollment__c/fields/SF_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SF_User_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SF_User_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Student_Course_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Course_Id__c</fullName>
    <externalId>true</externalId>
    <label>Student Course Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <label>Student ID</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SX_Course__c.field-meta.xml
<CustomField>
    <fullName>SX_Course__c</fullName>
    <label>Course</label>
    <referenceTo>SX_Courses__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SX_Enrollment_Date__c.field-meta.xml
<CustomField>
    <fullName>SX_Enrollment_Date__c</fullName>
    <label>Enrollment Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SX_percent_Completed__c.field-meta.xml
<CustomField>
    <fullName>SX_percent_Completed__c</fullName>
    <label>% Completed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/LMS_User__c.field-meta.xml
<CustomField>
    <fullName>LMS_User__c</fullName>
    <formula>CASE(RecordType.DeveloperName,
&apos;Employee&apos;, HYPERLINK(&apos;/&apos; &amp; Id, SF_User__r.FirstName &amp; &apos; &apos; &amp; SF_User__r.LastName,&apos;_self&apos;),
HYPERLINK(&apos;/&apos; &amp; Id, SF_Contact__r.FirstName &amp; &apos; &apos; &amp; SF_Contact__r.LastName,&apos;_self&apos;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LMS User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/LMS_User_Name__c.field-meta.xml
<CustomField>
    <fullName>LMS_User_Name__c</fullName>
    <formula>CASE(RecordType.DeveloperName,
&apos;Employee&apos;, SF_User__r.FirstName &amp; &apos; &apos; &amp; SF_User__r.LastName,
SF_Contact__r.FirstName &amp; &apos; &apos; &amp; SF_Contact__r.LastName
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>LMS User Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX LMS Users</relationshipLabel>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/User/fields/SX_Active_User__c.field-meta.xml
<CustomField>
    <fullName>SX_Active_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>SX Active User</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <label>SX LMS User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Enrollment_CTRL.cls
/**
 * @ Author: GRidowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-09-18 20:55:43
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:41:11
 * @ Description: Test class is Enrollment_CTRL_Test
 */

public with sharing class Enrollment_CTRL {
    @AuraEnabled(Cacheable=true)
    public static List<SX_Courses__c> getCourses(Id recordId, String searchTerm) {
        System.debug(recordId);
        System.debug(searchTerm);
        searchTerm = '%' + searchTerm + '%';
        if (recordId.getSobjectType() == Schema.Contact.getSObjectType()) {
            return [
                SELECT 
                    Name, SX_Course_ID__c, SX_Course_Image_URL__c, SX_Course_URL__c, SX_Course_Active__c, SX_Course_Description__c
                FROM SX_Courses__c
                WHERE SX_Course_Active__c = TRUE  AND Name LIKE :searchTerm AND
                    Id NOT IN (SELECT SX_Course__c FROM SX_Enrollment__c WHERE SF_Contact_Lookup__c = :recordId)
            ];
        } else {
            return [
                SELECT 
                    Name, SX_Course_ID__c, SX_Course_Image_URL__c, SX_Course_URL__c, SX_Course_Active__c, SX_Course_Description__c
                FROM SX_Courses__c
                WHERE SX_Course_Active__c = TRUE  AND Name LIKE :searchTerm AND
                    Id NOT IN (SELECT SX_Course__c FROM SX_Enrollment__c WHERE Student_ID__c = :recordId)
            ];
        }
    }

    @AuraEnabled(Cacheable=true)
    public static List<SX_LMS_User__c> getStudents(Id recordId, String searchTerm) {
        System.debug(searchTerm);
        searchTerm = '%' + searchTerm + '%';
        return [
            SELECT 
                Name, SX_User_ID__c, LMS_User__c, LMS_User_Name__c, RecordType.Name
            FROM SX_LMS_User__c
            WHERE   SX_Active_User__c = true AND LMS_User_Name__c LIKE :searchTerm AND
                    Id NOT IN (SELECT Student_ID__c FROM SX_Enrollment__c WHERE SX_Course__c = :recordId)
            ORDER BY LMS_User_Name__c
        ];
    }

    @AuraEnabled(Cacheable=false)
    public static Map<String, Map<String, String>> enrollCourses(String studentId, List<String> courseIds) {
        System.debug('studentId: ' + studentId);
        System.debug(JSON.serializePretty(courseIds));
        SX_LMS_User__c lmsUser = [SELECT SF_User__c, SF_Contact__c, RecordType.DeveloperName FROM SX_LMS_User__c WHERE SX_User_ID__c = :studentId LIMIT 1];
        Map<String, Map<String, String>> resultMap = SchooxAPI.assignCourses(studentId, courseIds);
        List<SX_Enrollment__c> enrollmentList = new List<SX_Enrollment__c>();
        for (Map<String, String> result : resultMap.values()) {
            String courseId = result.values()[0];
            String message = result.values()[1];
            if (message == 'User successfully assigned') {
                SX_Enrollment__c tempEnrollment = new SX_Enrollment__c(
                        Student_Course_Id__c = studentId + '#' + courseId,
                        Student_ID__r = new SX_LMS_User__c(SX_User_ID__c = studentId),
                        SX_Course__r = new SX_Courses__c(SX_Course_ID__c = courseId),
                        SX_percent_Completed__c = 0,
                        SX_Enrollment_Date__c = Date.today()
                );
                if (lmsUser.RecordType.DeveloperName == 'External') {
                    tempEnrollment.SF_Contact_Lookup__c = lmsUser.SF_Contact__c;
                } else {
                    tempEnrollment.SF_User_Lookup__c = lmsUser.SF_User__c;
                }
                enrollmentList.add(tempEnrollment);
            }
        }
        System.debug(JSON.serializePretty(enrollmentList));
        upsert enrollmentList Student_Course_Id__c;
        return resultMap;
    }

    @AuraEnabled(Cacheable=false)
    public static String enrollStudent(String courseId, String studentId) {
        return SchooxAPI.assignCourse(courseId, studentId);
    }

    @AuraEnabled(Cacheable=false)
    public static List<SX_Enrollment__c> updateEnrollment(String courseId, List<String> studentIds) {
        System.debug('<--------- updateEnrollment --------->');
        Map<String, SX_LMS_User__c> lmsUserById = new Map<String, SX_LMS_User__c>();
        for (SX_LMS_User__c lmsUser : [
            SELECT SX_User_ID__c, SF_User__c, SF_Contact__c, RecordType.DeveloperName
            FROM SX_LMS_User__c
            WHERE SX_User_ID__c IN :studentIds
        ]) {
            lmsUserById.put(lmsUser.SX_User_ID__c, lmsUser);
        }
        List<SX_Enrollment__c> enrollmentList = new List<SX_Enrollment__c>();
        for (String studentId : studentIds) {
            SX_Enrollment__c tempEnrollment = new SX_Enrollment__c(
                Student_Course_Id__c = studentId + '#' + courseId,
                Student_ID__r = new SX_LMS_User__c(SX_User_ID__c = studentId),
                SX_Course__r = new SX_Courses__c(SX_Course_ID__c = courseId),
                SX_percent_Completed__c = 0,
                SX_Enrollment_Date__c = Date.today()

            );
            SX_LMS_User__c lmsUser = lmsUserById.get(studentId);
            if (lmsUser.RecordType.DeveloperName == 'External') {
                tempEnrollment.SF_User_Lookup__c = lmsUser.SF_User__c;
            } else {
                tempEnrollment.SF_Contact_Lookup__c = lmsUser.SF_Contact__c;
            }
            enrollmentList.add(tempEnrollment);
        }
        System.debug(JSON.serializePretty(enrollmentList));
        upsert enrollmentList Student_Course_Id__c;
        return enrollmentList;
    }
}