force-app/main/default/objects/Contact/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX LMS User</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_User_Id__c.field-meta.xml
<CustomField>
    <fullName>SX_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>SX User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PersonAccount/recordTypes/PersonAccount.recordType-meta.xml
<RecordType>
    <fullName>PersonAccount</fullName>
    <active>true</active>
    <label>Person Account</label>
</RecordType>

force-app/main/default/objects/SX_Above_Unit__c/SX_Above_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Above Units along with corresponding Schoox IDs</description>
    <label>SX Above Unit</label>
    <nameField>
        <label>SX Above Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Above Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Above_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX LMS Users</relationshipLabel>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_Id__c.field-meta.xml
<CustomField>
    <fullName>SX_Id__c</fullName>
    <formula>SX_User_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SX Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-11-11 09:03:46
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:38:17
 * @ Description:
 */

@IsTest
public with sharing class TestDataFactory {
    private static final Integer DATA_SIZE = 5;

    public static List<Account> insertAccountData() {
        Account acc = new Account(
            Name = 'TEST ADMIN',
            Phone  = '12346789',
            AccountNumber = '123'
        );

        Id personAccountRecordTypeId =  Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('PersonAccount').getRecordTypeId();
        List<Account> testAccts = new List<Account>{acc};
        for(Integer i=0 ; i < DATA_SIZE ; i++) {
            Account tempAccount = new Account(
                FirstName  = 'TEST',
                LastName   = 'Account' + i,
                RecordTypeId = personAccountRecordTypeId,
                PersonEmail  = 'ridowan' + i + '@test.com',
                Phone  = '12346789'
            );
            testAccts.add(tempAccount);
        }
        insert testAccts;
        return testAccts;
    }
    
    public static List<Contact> insertContactData() {
        List<Account> testAccts = [SELECT Id FROM Account WHERE IsPersonAccount = FALSE];
        if (testAccts.isEmpty()) {
            testAccts = insertAccountData();
            testAccts = [SELECT Id FROM Account WHERE IsPersonAccount = FALSE];
        }
        List<Contact> testContacts = new List<Contact>();
        for(Integer i=0 ; i < testAccts.size() ; i++) {
            Contact con = new Contact(
                AccountId  = testAccts.get(Math.mod(i, testAccts.Size())).Id,
                FirstName  = 'Ridowan' + i,
                LastName   = 'Ahmed' + i,
                Salutation = 'Mr.', 
                Email	   = i + 'ridowan@mi6.co.uk',
                Phone	   = '0881234567',
                MobilePhone= '0631226777',
                MailingCountry = 'United States'
            );
            testContacts.add(con);
        }
        testContacts.get(0).SX_User_Id__c = '123';
        insert testContacts;
        return testContacts;
    }

    public static List<SX_LMS_User__c> insertLMSUserData() {
        List<Contact> testContacts = [SELECT Name FROM Contact];
        if (testContacts.isEmpty()) {
            testContacts = insertContactData();
        }
        List<SX_LMS_User__c> lmsList = new List<SX_LMS_User__c>();
        for(Integer i=0 ; i < testContacts.size() ; i++) {
            SX_LMS_User__c lms = new SX_LMS_User__c(
                SF_Contact__c  = testContacts.get(i).Id
            );
            lmsList.add(lms);
        }
        lmsList.get(0).SX_User_ID__c = '123';
        lmsList.get(0).SF_Contact__c = null;
        lmsList.get(0).SF_User__c = UserInfo.getUserId();
        insert lmsList;
        return lmsList;
    }

    public static List<SX_Courses__c> insertCourseData() {
        List<SX_Courses__c> courseList = new List<SX_Courses__c>();
        for(Integer i=0 ; i < DATA_SIZE ; i++) {
            SX_Courses__c testCourse = new SX_Courses__c(
                Name  = 'Test ' + i,
                SX_Course_ID__c = '32' + i
            );
            courseList.add(testCourse);
        }
        insert courseList;
        System.debug(JSON.serializePretty(courseList));
        return courseList;
    }

    public static List<SX_Above_Unit__c> insertAboveUnitData() {
        List<SX_Above_Unit__c> aboveUnitList = new List<SX_Above_Unit__c>();
        for(Integer i=0 ; i < DATA_SIZE ; i++) {
            SX_Above_Unit__c tempAboveUnit = new SX_Above_Unit__c(
                Name  = 'Test ' + i,
                SX_ID__c = '10' + i
            );
            aboveUnitList.add(tempAboveUnit);
        }
        insert aboveUnitList;
        return aboveUnitList;
    }
}