force-app/main/default/objects/Contact/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SX LMS User</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/SX_User_Id__c.field-meta.xml
<CustomField>
    <fullName>SX_User_Id__c</fullName>
    <externalId>true</externalId>
    <label>SX User Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_Courses__c/SX_Courses__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Courses</description>
    <label>SX Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Courses__c/fields/SX_Course_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_Course_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX Course ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Enrollment_CTRL_Test.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-11-17 23:01:23
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:40:59
 * @ Description: Test class for Enrollment_CTRL
 */

@isTest
private class Enrollment_CTRL_Test {
    @testSetup static void setup() {
        TestDataFactory.insertContactData();
        TestDataFactory.insertCourseData();
        TestDataFactory.insertLMSUserData();
    }

    @isTest static void testGetData() {
        System.debug('==================Enrollment_CTRL_Test GetData=====================');
        Contact testCon = [SELECT SX_User_Id__c FROM Contact WHERE SX_User_Id__c != null LIMIT 1];
        SX_LMS_User__c testLMSUser = [SELECT SX_User_Id__c FROM SX_LMS_User__c WHERE SX_User_Id__c != null LIMIT 1];
        SX_Courses__c testCourse = [SELECT SX_Course_ID__c FROM SX_Courses__c WHERE SX_Course_ID__c != null LIMIT 1];
        Test.StartTest();

        Enrollment_CTRL.getCourses(testCon.Id, 'Test');
        Enrollment_CTRL.getCourses(testLMSUser.Id, 'Test');
        Enrollment_CTRL.getStudents(testLMSUser.Id, 'Test');

        SchooxAPI.testResponse = SchooxAPI_Test.getMockResponse(200, SchooxAPI.ApiType.UserCourse);
        Enrollment_CTRL.enrollStudent(testCourse.SX_Course_ID__c, testCon.SX_User_Id__c);
        Enrollment_CTRL.enrollCourses(testLMSUser.SX_User_Id__c, new List<String>{testCourse.SX_Course_ID__c});
        Enrollment_CTRL.updateEnrollment(testCourse.SX_Course_ID__c, new List<String>{testLMSUser.SX_User_Id__c});

        Test.StopTest();
    }
}