force-app/main/default/objects/SX_Unit__c/SX_Unit__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS Units along with corresponding Schoox IDs</description>
    <label>SX Unit</label>
    <nameField>
        <label>SX Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Unit__c/fields/SX_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX ID</label>
    <length>99</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetAllUnitsEXT_Test.cls
/**
 * @ Author: Gary Guthrie
 * @ Create Time: 2022-11-18 00:01:06
 * @ Modified by: Gary Guthrie
 * @ Modified time: 2022-11-18 06:49:51
 * @ Description: Test class for GetAllUnitsEXT
 */

@isTest
private class GetAllUnitsEXT_Test {
    @testSetup static void setup() {
        TestDataFactory.insertCourseData();
    }

    static testMethod void testController (){
        List<SX_Unit__c> testUnitList = [SELECT SX_ID__c FROM SX_Unit__c];
        Test.startTest();
        SchooxAPI.testResponse = SchooxAPI_Test.getMockResponse(200, SchooxAPI.ApiType.AllUnit);
        ApexPages.StandardSetController sc = new ApexPages.StandardSetController(testUnitList);
        GetAllUnitsEXT unitExt = new GetAllUnitsEXT(sc);
        unitExt.getBack();
        Test.stopTest();
    }
}