force-app/main/default/objects/SX_Enrollment__c/SX_Enrollment__c.object-meta.xml
<CustomObject>
    <description>Tracks the Schoox LMS course enrollment for each learner along with key statistics.</description>
    <label>SX Enrollment</label>
    <nameField>
        <label>SX Enrollment ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SX Enrollments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_Enrollment__c/fields/SF_Contact_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact Lookup</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/SF_User_Lookup__c.field-meta.xml
<CustomField>
    <fullName>SF_User_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User Lookup</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Student_Course_Id__c.field-meta.xml
<CustomField>
    <fullName>Student_Course_Id__c</fullName>
    <externalId>true</externalId>
    <label>Student Course Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_Enrollment__c/fields/Student_ID__c.field-meta.xml
<CustomField>
    <fullName>Student_ID__c</fullName>
    <label>Student ID</label>
    <referenceTo>SX_LMS_User__c</referenceTo>
    <relationshipLabel>SX Enrollments</relationshipLabel>
    <relationshipName>SX_Enrollments</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/SX_LMS_User__c.object-meta.xml
<CustomObject>
    <description>Master list of Schoox LMS learners</description>
    <label>SX LMS User</label>
    <nameField>
        <displayFormat>SLU-{0000}</displayFormat>
        <label>SX LMS User Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SX LMS Users</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_Contact__c.field-meta.xml
<CustomField>
    <fullName>SF_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SX LMS Users</relationshipLabel>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SF_User__c.field-meta.xml
<CustomField>
    <fullName>SF_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SF User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SX_LMS_Users</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SX_LMS_User__c/recordTypes/External.recordType-meta.xml
<RecordType>
    <fullName>External</fullName>
    <active>true</active>
    <label>External</label>
</RecordType>

force-app/main/default/objects/User/fields/SX_LMS_User__c.field-meta.xml
<CustomField>
    <fullName>SX_LMS_User__c</fullName>
    <label>SX LMS User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/SX_User_ID__c.field-meta.xml
<CustomField>
    <fullName>SX_User_ID__c</fullName>
    <externalId>true</externalId>
    <label>SX User ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/GetUserCourseBatch.cls
/**
 * @ Author: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Create Time: 2022-10-11 16:04:22
 * @ Modified by: Ridowan Ahmed (ridowan.dev@gmail.com)
 * @ Modified time: 2024-09-03 18:42:44
 * @ Description: Test class is GetUserCourseBatch_Test
 * new GetUserCourseBatch().execute(null);
 * Id batchJobId = Database.executeBatch(new GetUserCourseBatch(), 5);
 * System.schedule('Schoox User Courses Sync', '0 0 06,18 ? * MON-FRI', new GetUserCourseBatch());
 */

public without sharing class GetUserCourseBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Schedulable{
    public Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Name, SX_User_ID__c, SF_Contact__c, SF_User__c, RecordType.DeveloperName ';
        query += 'FROM SX_LMS_User__c ';
        query += 'WHERE ';
        query += 'SX_User_ID__c != null';
        // query += ' AND Id IN (SELECT Student_ID__c FROM SX_Enrollment__c)';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SX_LMS_User__c> lmsUserList) {
        List<SX_Enrollment__c> enrollmentListToUpdate = new List<SX_Enrollment__c>();
        for (SX_LMS_User__c lmsUser : lmsUserList) {
            List<SX_Enrollment__c> enrollmentList = SchooxAPI.getUserCourse(lmsUser.SX_User_ID__c);
            // System.debug(JSON.serializePretty(enrollmentList));
            if (lmsUser.RecordType.DeveloperName == 'External') {
                for (SX_Enrollment__c enrollment : enrollmentList) {
                    enrollment.SF_Contact_Lookup__c = lmsUser.SF_Contact__c;
                }
            } else {
                for (SX_Enrollment__c enrollment : enrollmentList) {
                    enrollment.SF_User_Lookup__c = lmsUser.SF_User__c;
                }
            }
            System.debug(JSON.serializePretty(enrollmentList));
            enrollmentListToUpdate.addAll(enrollmentList);
        }
        if (!enrollmentListToUpdate.isEmpty()) {
            upsert enrollmentListToUpdate Student_Course_Id__c;
            System.debug(enrollmentListToUpdate.size() + ' Enrollment updated');
        }
    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Execution Finish');
    }

    public void execute(SchedulableContext sc) {
        Id batchJobId = Database.executeBatch(new GetUserCourseBatch(), 90);
        System.debug('batchJobId: ' + batchJobId);
    }
}